(function(){
"use strict";
var T={
ko:{
nav_home:"홈",nav_about:"회사소개",nav_products:"제품소개",nav_parts:"부품소개",nav_gallery:"시공갤러리",nav_tech:"기술",nav_manual:"사용방법",nav_customer:"고객센터",nav_notice:"공지사항",nav_board:"게시판",nav_archive:"인증현황",nav_inquiry:"시공 사례 / 견적 상담",nav_contact:"Contact Us",nav_core_tech:"코어 기술",nav_process:"프로세스",nav_core_desc:"360° 스윙, 간편청소, FVD 방화댐퍼, 맞춤제작",nav_process_desc:"현장실측부터 시공·사후관리까지 4단계",nav_manual_desc:"제품 설치·유지보수 비주얼 가이드",nav_notice_desc:"중요공지, 이벤트 확인하세요.",nav_board_desc:"기술정보, 시공사례, 제품소식",nav_archive_desc:"특허, 인증서 등",nav_inquiry_desc:"매장 규모별 맞춤 설계",
hero_tag:"SINCE 2007 · YUSUNG ACE",hero_title1:"대한민국 덕트",hero_title2:"No.1",hero_sub:"오늘을 이끄는 원동력.",hero_scroll1a:"새로운 환경, 새로운 기술로",hero_scroll1b:"한걸음 앞서갑니다.",hero_scroll2a:"신뢰와 나눔 속에",hero_scroll2b:"사랑받는 기업으로.",
feat1_title:"360° 스윙",feat1_desc:"시계추 모양으로 360° 자유 회전. 파이프가 고정되어 있지 않아 부러질 염려 없이 편리합니다.",feat2_title:"F.V.D 방화담파",feat2_desc:"풍속조절 겸용 방화담파로 화재 시 자동 차단. 200~220도에서 닫혀 화재 확산을 방지합니다.",feat3_title:"분리청소 가능",feat3_desc:"도구 없이 손으로 분리. 매일 세척 가능한 위생 구조입니다. 터치분리로 상부 파이프도 청소 가능.",feat4_title:"상하작동 텐션",feat4_desc:"베어링 장력 조절 + 스톱바 브레이크로 안전한 높이 조절. 맞춤 기장 제작도 가능합니다.",
fim_tag:"FEATURES IN MOTION",fim_title_a:"디테일을 ",fim_title_b:"움직임으로",fim_title_c:" 확인하세요.",fim_desc:"4가지 핵심 기술이 실제로 어떻게 작동하는지, 가만히 보고만 있어도 느껴집니다.",fim_card1_tag:"01 / SWING",fim_card1_title:"360° 자유 스윙",fim_card1_desc:"텐션 나사 방식으로 상·하·좌·우 360° 완전 자유 회전. 접시는 움직여도 파이프는 제자리를 유지합니다.",fim_card2_tag:"02 / CLEAN",fim_card2_title:"원터치 분리청소",fim_card2_desc:"나사 한 바퀴면 상부 파이프까지 통째 분리. 내부 기름때를 직접 확인하며 매일 세척 가능합니다.",fim_card3_tag:"03 / SAFETY",fim_card3_title:"안전·유지관리 옵션",fim_card3_desc:"FVD방화댐퍼: 200~220도에서 댐퍼가 닫혀 화재 예방. 터치분리로 상부 파이프도 청소 가능.",fim_card4_tag:"04 / CUSTOM",fim_card4_title:"맞춤형 제작",fim_card4_desc:"필요하신 기장으로 맞춤 제작이 가능합니다. 기본기장 L1800 기준으로 절단·연장 가능.",
www_tag:"WHERE WE WORK",www_title_a:"대한민국의 ",www_title_b:"불 앞에서",www_title_c:".",www_desc:"프랜차이즈 주방부터 거친 공정의 제조 현장, 정밀한 연구소까지. 유성에이스는 매일 수많은 전문가들의 작업 환경을 쾌적하게 지켜내고 있습니다.",www_case1_tag:"USE CASE 01",www_case1_title:"직화 고깃집",www_case1_desc:"테이블마다 떨어지는 기름을 방지하며 360도 스윙으로 자유롭게 연기 흡입 가능.",www_case1_btn:"파이프 시리즈 보기",www_case2_tag:"USE CASE 02",www_case2_title:"대형 프랜차이즈",www_case2_desc:"매장 전체 통일 규격 · 부품 교체 표준화. F.V.D 방화담파로 다점포 안전 일괄 관리.",www_case2_btn:"LED 조명 보기",www_case3_tag:"USE CASE 03",www_case3_title:"공장 / 연구실",www_case3_desc:"연기가 가득한 현장에서도, 정밀한 환기가 필요한 연구실에서도 환기 솔루션을 제공합니다.",www_case3_btn:"후레쉬볼 갓 자바라 보기",www_cta_text:"우리 매장에 어떤 모델이 맞는지 모르시겠나요?",www_cta_btn:"무료 상담 신청",
stmt_tag:"A NEW STANDARD",stmt_title1:"신개념 유성에이스,",stmt_title2:"식당의 미래",stmt_title3:"를 열다.",stmt_desc:"직화기 닥트 시설의 흐름이 변해가는 시대. 심혈을 기울여 완성된 유성에이스만의 독보적 기술력을 만나보세요.",stmt_chip1:"360° SWING",stmt_chip2:"F.V.D 방화담파",stmt_chip3:"분리 청소",stmt_chip4:"상하 텐션",stmt_chip5:"친환경 설계",
gp_tag:"REAL CONSTRUCTION",gp_title1:"20년 동안 쌓아온",gp_title2:"진짜 현장 사진.",gp_btn:"전체 갤러리 보기",
vid_tag:"YUSUNG ACE IN ACTION",vid_title1:"유성에이스 후드,",vid_title2:"움직이는 모습 그대로.",vid_desc:"360° 스윙, 상하 텐션, FVD 방화댐퍼의 작동을 영상으로 만나보세요. 20년 노하우가 만든 부드럽고 정확한 움직임.",vid_btn:"네이버 블로그에서 영상 보기",
about_hero_tag:"SINCE 2007 · ABOUT US",about_hero_t1:"신뢰와 나눔 속에",about_hero_t2:"사랑받는 기업으로.",about_hero_desc:"업계가 뒤따라오는 혁신의 시작점, 그 중심에는 언제나 유성에이스가 있습니다. 속도가 아닌 올바른 방향으로 세운 우리만의 기준은 모방할 수 없는 자부심이 되어 고객님의 신뢰에 보답합니다.",about_ceo_tag:"CEO MESSAGE",about_ceo_label:"대표이사",about_ci_tag:"COMPANY INFO",about_ci_title:"회사 정보",about_ci_ceo_title:"대표이사",about_ci_biz_label:"사업자등록번호",about_loc_tag:"LOCATION",about_loc_title:"찾아오시는 길",about_naver_map:"네이버지도",about_kakao_map:"카카오맵",about_promise_tag:"OUR PROMISE",about_promise_t1:"최고의 기술과 품질로",about_promise_t2:"SERVICE를 통한 고객만족 실현.",about_promise_desc:"친환경 도시개발에 앞장서가는 기업, 유성에이스는 2007년부터 한길만 걸어온 대한민국 덕트 No.1입니다.",about_contact_tag:"CONTACT US",about_contact_title:"문의하기",about_contact_desc:"견적, 설치, A/S 등 궁금한 점을 남겨주시면 빠르게 연락드리겠습니다.",about_form_submit:"문의 접수하기",about_success_title:"문의가 접수되었습니다!",about_success_desc:"빠른 시간 내에 담당자가 연락드리겠습니다.",
prod_hero_tag:"PRODUCT LINEUP · 148 MODELS",prod_hero_t1:"148가지 제품,",prod_hero_t2:"하나의 장인정신.",prod_hero_desc:"갤럭시 A·B·C·D 타입, 양옆태엽, LED조명, LED우주선, 스파이얼, 파이프, 후레쉬볼까지 — 유성에이스의 전 제품 라인업을 실제 사진과 함께 살펴보세요.",prod_cta_tag:"NEED HELP CHOOSING?",prod_cta_title:"매장에 맞는 제품, 직접 상담드립니다.",prod_cta_desc:"20년 노하우로 매장 규모·화로 종류·천정고에 맞춤 최적의 제품을 추천해드립니다.",prod_cta_gallery:"시공 갤러리 보기",
parts_tag:"PARTS CATALOG · 50 ITEMS",parts_hero_title:"부품소개",parts_hero_desc:"유성에이스 후드를 구성하는 모든 부품을 한눈에. 각 부품의 실물 누끼 사진으로 확인하세요.",
manual_hero_title:"사용방법",manual_hero_desc:"유성에이스 제품의 올바른 사용 및 유지보수 방법입니다.",
gallery_hero_tag:"CONSTRUCTION GALLERY",gallery_hero_desc:"유성에이스가 시공한 직화기 후드 라인업. 갤럭시 시리즈, 아크릴등, 우주선 후드, 외부태엽 등 다양한 현장 사진을 만나보세요.",
process_hero_t1:"현장실측부터 사후관리까지,",process_hero_t2:"4단계 원스톱 시스템.",process_hero_desc:"20년 노하우의 전문가가 직접 방문하여 매장에 최적화된 솔루션을 설계·제작·시공합니다.",process_tag:"OUR PROCESS",process_step1_title:"현장 실측 / 상담",process_step1_desc:"20년 노하우의 전문가가 직접 방문해 매장 규모·화로 종류·천정고를 측정합니다. 현장 환경에 맞는 최적의 후드 시스템을 제안합니다.",process_step2_title:"맞춤 설계·견적",process_step2_desc:"갤럭시 A~D 중 매장에 최적인 모델을 추천하고 도면·견적서를 제공합니다. 천정고, 화로 배치, 동선을 모두 고려한 맞춤 설계입니다.",process_step3_title:"자체 공장 제작",process_step3_desc:"유성에이스 자체 공장에서 정밀 제작 후 현장으로 직배송합니다. 나사 하나까지 100% 국내 자체 생산, 품질에 대한 자부심입니다.",process_step4_title:"시공 및 사후관리",process_step4_desc:"전문 기사 시공 + F.V.D 방화담퍼 점검 + 부분 특허 부품 A/S 지원. 시공 후에도 유지보수까지 책임지는 원스톱 서비스입니다.",process_cta:"무료 현장 실측 신청하기",process_cta_text:"지금 바로 상담받으세요",process_cta_btn:"견적 상담",
tech_hero_tag:"TECHNOLOGY DEEP DIVE",tech_hero_t1:"8가지 핵심 기술,",tech_hero_t2:"하나의 후드 안에.",tech_hero_desc:"20년 동안 한길만 걸어온 유성에이스가 직접 설계하고, 매장에서 검증한 핵심 기술들을 모두 공개합니다.",tech_tag:"CORE TECHNOLOGY",tech_title:"유성에이스만의 핵심 기술",tech_impact:"자체공장에서 직접 설계하고 생산합니다.",tech_3d_title:"3D 후드 시스템",tech_stat1_label:"특허 기술",tech_stat1_val:"5건+",tech_stat2_label:"모델 라인업",tech_stat2_val:"148종",tech_stat3_label:"시공 실적",tech_stat3_val:"전국",tech_stat4_label:"업력",tech_stat4_val:"20년",
footer_company:"(주) 유성에이스",footer_desc:"대한민국 덕트 No.1 — 2007년부터 한길만 걸어온 직화기 후드 전문 기업. 새로운 환경, 새로운 기술로 한걸음 앞서갑니다.",footer_addr:"경기 파주시 파주읍 센트럴산단1로 103",footer_addr_label:"주소",footer_tel:"TEL",footer_fax:"FAX",footer_ceo:"대표",footer_ceo_name:"박진선",footer_biz:"사업자등록번호",footer_rights:"All rights reserved.",footer_no1:"대한민국 덕트 No.1",
lang_ko:"한국어",lang_en:"English",lang_ja:"日本語",lang_vi:"Tiếng Việt",lang_zh:"中文",
nav_about_ceo:"CEO 인사말",nav_about_ceo_sub:"신개념 유성에이스의 약속",nav_about_map:"찾아오시는 길",nav_about_map_sub:"본사 및 공장 위치",
mega_cat1:"갤럭시 A~D타입",mega_cat1_sub:"스윙태엽/FVD/유지망 통합",mega_cat2:"양옆태엽 BEST",mega_cat2_sub:"양옆태엽 스윙 시리즈",mega_cat3:"LED 조명 / 우주선",mega_cat3_sub:"LED/할로겐 등제품 및 아크릴등",mega_cat4:"파이프 / 스파이얼",mega_cat4_sub:"스텐파이프(도금/도장) · 스파이럴",mega_cat5:"후레쉬볼 / 주름관",mega_cat5_sub:"플렉시블 연결관",mega_view_all:"모두 보기 →",
cta_tag:"SINCE 2007 · PROVEN QUALITY",cta_title1:"한 번 쓰면,",cta_title2:"다시 못 돌아갑니다.",cta_desc:"마케팅 없이 입소문만으로 성장한 품질의 차이, 직접 경험해 보세요.",cta_btn_products:"제품 라인업 보기",cta_btn_inquiry:"견적 문의",
core_title:"유성에이스 후드의 장점.",core_desc:"직화기 닥트 시설의 새로운 흐름. 불편함을 개선하고 위생과 안전, 시각적 아름다움을 모두 잡았습니다.",core_label_upper:"상부 파이프",core_label_fvd:"방화담퍼",core_label_lower:"하부 파이프",core_label_cap:"나팔캡 기름받이",core_tagline:"흔들려도 꺾이지 않는 기술력",
core_f1_title:"01 테이블 기준 360° 스윙",core_f1_desc:"파이프가 고정되어 있지 않고 수직에서 시계추 모양으로 360° 회전 되어 부러질 염려가 없어 편리합니다.",core_f2_title:"02 간편한 내부청소",core_f2_desc:"하부 파이프를 간단히 분리할 수 있어서 누구나 손쉽게 파이프 내부 청소가 가능합니다.",core_f3_title:"03 안전 · 유지관리 옵션",core_f4_title:"04 맞춤형 제작",core_f4_desc:"필요하신 기장으로 맞춤 제작이 가능합니다. 기본기장 L1800 기준으로 절단 혹은 연장이 가능하여 다양한 현장에 대응 가능합니다.",
impact_copy:"대한민국의 기술 유성에이스 세계로 나아갑니다.",stat_products:"제품 라인업",stat_engineering:"엔지니어링",stat_swing:"스윙 시스템",stat_domestic:"국내 제조",
about_ceo_name:"박진선",about_ceo_p1:"현장의 가치를 기술로 실현하는 환기 솔루션의 리더, 유성에이스입니다. 저희는 창립 이래 '현장 중심의 기술력'과 '고객 최우선의 가치'를 바탕으로 주방 환기 시스템의 혁신을 이끌어왔습니다.",about_ceo_p2:"설계부터 제조, 그리고 실제 현장 시공에 이르기까지 나사 하나, 피스 하나의 디테일도 놓치지 않는 정교함은 유성에이스가 지켜온 자부심입니다. 국내에서 직접 생산하는 제조사이며, 고객과 사용자의 입장에서 현장에서 발생하는 수많은 변수와 고충을 해결하는 '파트너'로서 고객사와 함께 성장해왔습니다.",about_ceo_p3:"유성에이스의 모든 제품은 사용자의 편의성을 극대화한 사용자 중심 설계를 지향합니다. 실제 현장에서 기기를 다루는 분들의 목소리에 귀를 기울여, 더 안전하고 효율적인 환기 환경을 만드는 것이 우리의 사명입니다.",about_ceo_p4:"앞으로도 유성에이스는 끊임없는 연구개발과 철저한 품질 관리를 통해 대한민국 주방 환기 문화를 선도하는 최고의 환기 솔루션을 제공할 것을 약속드립니다. 변함없는 믿음과 성원을 보내주시는 고객 여러분께 진심으로 감사의 말씀을 올립니다.",
about_addr1:"경기 파주시 파주읍 센트럴산단1로 103",about_addr2:"(봉암리 1371-9)",about_ci_name:"유성에이스",about_ci_ceo:"박진선",
form_name:"이름",form_phone:"연락처",form_company:"업체 / 매장명",form_type:"문의 유형",form_type_quote:"견적 문의",form_type_install:"설치 문의",form_type_as:"A/S 문의",form_type_other:"기타 문의",form_content:"문의 내용",form_phone_alt:"또는 1588-9123 으로 전화주세요",form_new_inquiry:"새 문의 작성",
prod_stat1:"11개 카테고리",prod_stat2:"148종 실제 사진",prod_stat3:"20년 기술 노하우",prod_no_items:"해당 카테고리 제품이 없습니다.",prod_filter_all:"전체",prod_cta_t1:"매장 유형별",prod_cta_t2:"맞춤 추천 라인업.",prod_parts_t1:"148가지 제품,",prod_parts_t2:"하나의 표준 부품.",prod_consult_t1:"매장에 어울리는 모델,",prod_consult_t2:"함께 골라드립니다.",prod_consult_desc:"20년 노하우로 매장 규모, 메뉴, 인테리어에 맞는 최적 라인을 추천해 드립니다.",prod_consult_phone:"1588-9123 전화 상담",prod_consult_about:"회사 정보 보기",
manual_f1_title:"기름유도장치 (기름받이속)",manual_f1_desc:"사용 중에 기름이 전혀 흐르지 않습니다. 일체형 성형 기름받이가 후드 내부의 기름을 안전하게 모아 위생적으로 관리합니다.",manual_f1_tag:"기름 흘림 ZERO",manual_f2_title:"무소음 흡입 설계",manual_f2_desc:"흡입구 공기압이 강해도 휘파람 소리가 나지 않습니다. 정밀한 에어플로우 설계로 매장 내 쾌적한 환경을 유지합니다.",manual_f2_tag:"소음 없는 강력 흡입",manual_f3_title:"나사타입 간편 분리",manual_f3_desc:"상하부를 연결하는 파이프링이 나사타입으로 조립되어 분리가 쉬우며, 누구나 손쉽게 내부청소가 가능합니다.",manual_f3_tag:"도구 없이 손쉬운 분리",manual_f4_title:"유지망필터",manual_f4_desc:"기름을 여과하여 모터 및 덕트 내부를 청결하게 합니다. 모터 수명을 오래 유지하고, 화재를 예방하는 이중 효과가 있습니다.",manual_f4_tag:"모터수명 연장 + 화재예방",manual_f5_title:"360° 자유 스윙",manual_f5_desc:"파이프가 고정되어 있지 않고 자유롭게 스윙(swing)되어 편리합니다. 시계추처럼 부드럽게 회전하여 부러질 염려가 전혀 없으며, 테이블 기준으로 어디서든 자유롭게 사용할 수 있습니다.",manual_f5_tag1:"파이프 파손 ZERO",manual_f5_tag2:"360° 회전",manual_f5_tag3:"시계추 원리",manual_video_link:"유성에이스 공식 영상 보기",
gallery_hero_t1:"20년의 시공,",gallery_hero_t2:"전국 곳곳에 있습니다.",gallery_source:"사진 출처: usungace.com 공식 포트폴리오 · 사진 클릭 시 상세 정보",gallery_modal_desc:"설명",gallery_modal_features:"핵심 특징",gallery_modal_spec:"제품 사양",gallery_modal_tags:"태그",
tech_hero_desc2:"20년 동안 한길만 걸어온 유성에이스가 직접 설계하고, 매장에서 검증한 핵심 기술들을 모두 공개합니다.",
notice_tag:"NOTICE · 공지사항",notice_title:"유성에이스 소식",notice_desc:"중요한 공지, A/S 일정, 이벤트 소식을 한곳에서 확인하세요.",
board_tag:"BOARD · 게시판",board_title:"게시판",board_desc:"유성에이스의 기술정보, 시공사례, 제품소식을 블로그처럼 확인하세요.",board_sort_latest:"최신순",board_sort_views:"조회순",board_sort_num:"번호순",board_col_no:"번호",board_col_cat:"분류",board_col_title:"제목",board_col_author:"작성자",board_col_date:"등록일",board_col_views:"조회",
archive_tag:"CERTIFICATIONS · 인증현황",archive_title:"인증현황",archive_desc:"유성에이스가 보유한 특허, 디자인등록, 인증서를 확인하세요.",archive_all:"전체 자료",archive_filter_patent:"특허",archive_filter_design:"디자인등록",archive_filter_cert:"인증서",archive_stat_patent:"특허 보유",archive_stat_design:"디자인등록",archive_stat_cert:"인증서",archive_stat_knowhow:"기술 노하우",
footer_copyright:"© 2026 YUSUNG ACE / 유성에이스. All rights reserved.",
mega_categories:"카테고리",mega_full_list:"전체 제품",mega_filtered:"필터 결과"
},

en:{
nav_home:"Home",nav_about:"About Us",nav_products:"Products",nav_parts:"Parts",nav_gallery:"Gallery",nav_tech:"Technology",nav_manual:"Manual",nav_customer:"Support",nav_notice:"Notice",nav_board:"Board",nav_archive:"Archive",nav_inquiry:"Projects / Quote",nav_contact:"Contact Us",nav_core_tech:"Core Technology",nav_process:"Process",nav_core_desc:"360° Swing, Easy Clean, FVD Fire Damper, Custom Built",nav_process_desc:"4 Steps from Site Survey to After-Service",nav_manual_desc:"Visual Guide for Installation & Maintenance",nav_notice_desc:"Important notices and event updates",nav_board_desc:"Tech info, project cases, product news",nav_archive_desc:"Patents, certifications, and more",nav_inquiry_desc:"Custom design by store size",
hero_tag:"SINCE 2007 · YUSUNG ACE",hero_title1:"Korea's Duct",hero_title2:"No.1",hero_sub:"The driving force behind today.",hero_scroll1a:"With new environments and new technology,",hero_scroll1b:"we stay one step ahead.",hero_scroll2a:"Built on trust and sharing,",hero_scroll2b:"a company people love.",
feat1_title:"360° Swing",feat1_desc:"Free 360° pendulum rotation. The unfixed pipe design eliminates breakage and ensures easy handling.",feat2_title:"F.V.D Fire Damper",feat2_desc:"Dual-purpose fire damper with airflow control. Automatically shuts at 200–220°C to prevent fire spread.",feat3_title:"Easy Disassembly & Clean",feat3_desc:"Hand-detachable without tools. Hygienic design allows daily cleaning. Touch-release for upper pipes too.",feat4_title:"Adjustable Tension",feat4_desc:"Bearing tension adjustment + stop bar brake for safe height control. Custom lengths available.",
fim_tag:"FEATURES IN MOTION",fim_title_a:"See the ",fim_title_b:"details",fim_title_c:" in action.",fim_desc:"Watch how our four core technologies actually work — you can feel the difference just by looking.",fim_card1_tag:"01 / SWING",fim_card1_title:"360° Free Swing",fim_card1_desc:"Tension-screw mechanism enables full 360° rotation in all directions. The disc moves, but the pipe stays perfectly in place.",fim_card2_tag:"02 / CLEAN",fim_card2_title:"One-Touch Disassembly",fim_card2_desc:"A single screw turn detaches the entire upper pipe assembly. Inspect and wash away grease buildup daily.",fim_card3_tag:"03 / SAFETY",fim_card3_title:"Safety & Maintenance Options",fim_card3_desc:"FVD Fire Damper: closes at 200–220°C to prevent fire. Touch-release enables upper pipe cleaning.",fim_card4_tag:"04 / CUSTOM",fim_card4_title:"Custom Manufacturing",fim_card4_desc:"Built to the exact length you need. Standard L1800 base — can be cut or extended.",
www_tag:"WHERE WE WORK",www_title_a:"At the ",www_title_b:"heart of the flame",www_title_c:".",www_desc:"From franchise kitchens to heavy-duty manufacturing floors and precision laboratories — YUSUNG ACE keeps the work environments of countless professionals clean and comfortable every day.",www_case1_tag:"USE CASE 01",www_case1_title:"Charcoal BBQ",www_case1_desc:"Prevents grease drips at each table with 360° swing for free-direction smoke extraction.",www_case1_btn:"View Pipe Series",www_case2_tag:"USE CASE 02",www_case2_title:"Large Franchise",www_case2_desc:"Unified specs across all locations with standardized parts replacement. F.V.D fire damper for multi-store safety management.",www_case2_btn:"View LED Lighting",www_case3_tag:"USE CASE 03",www_case3_title:"Factory / Lab",www_case3_desc:"Ventilation solutions for smoke-filled factories and precision research labs alike.",www_case3_btn:"View Fresh Ball Hood Flex",www_cta_text:"Not sure which model fits your store?",www_cta_btn:"Free Consultation",
stmt_tag:"A NEW STANDARD",stmt_title1:"A new YUSUNG ACE,",stmt_title2:"the future of dining",stmt_title3:" has arrived.",stmt_desc:"In an era where charcoal grill duct systems are evolving, discover the unmatched technology perfected by YUSUNG ACE.",stmt_chip1:"360° SWING",stmt_chip2:"F.V.D Fire Damper",stmt_chip3:"Easy Clean",stmt_chip4:"Adjustable Tension",stmt_chip5:"Eco-Friendly Design",
gp_tag:"REAL CONSTRUCTION",gp_title1:"20 years of building",gp_title2:"real site photos.",gp_btn:"View Full Gallery",
vid_tag:"YUSUNG ACE IN ACTION",vid_title1:"YUSUNG ACE hoods,",vid_title2:"see them in motion.",vid_desc:"Watch the 360° swing, adjustable tension, and FVD fire damper in action. Smooth and precise movement built on 20 years of expertise.",vid_btn:"Watch on Naver Blog",
about_hero_tag:"SINCE 2007 · ABOUT US",about_hero_t1:"Built on trust and sharing,",about_hero_t2:"a company people love.",about_hero_desc:"At the heart of industry-leading innovation stands YUSUNG ACE. Our standards, built on the right direction rather than speed, have become an irreplaceable source of pride that repays our customers' trust.",about_ceo_tag:"CEO MESSAGE",about_ceo_label:"CEO",about_ci_tag:"COMPANY INFO",about_ci_title:"Company Information",about_ci_ceo_title:"CEO",about_ci_biz_label:"Business Reg. No.",about_loc_tag:"LOCATION",about_loc_title:"Directions",about_naver_map:"Naver Map",about_kakao_map:"Kakao Map",about_promise_tag:"OUR PROMISE",about_promise_t1:"With the finest technology and quality,",about_promise_t2:"realizing customer satisfaction through service.",about_promise_desc:"Leading eco-friendly urban development since 2007, YUSUNG ACE is Korea's No.1 duct manufacturer.",about_contact_tag:"CONTACT US",about_contact_title:"Contact Us",about_contact_desc:"Leave your questions about quotes, installation, or A/S and we'll get back to you promptly.",about_form_submit:"Submit Inquiry",about_success_title:"Your inquiry has been submitted!",about_success_desc:"A representative will contact you shortly.",
prod_hero_tag:"PRODUCT LINEUP · 148 MODELS",prod_hero_t1:"148 products,",prod_hero_t2:"one craftsmanship.",prod_hero_desc:"Galaxy A·B·C·D types, side springs, LED lighting, LED UFO, spiral, pipes, fresh balls and more — explore the full YUSUNG ACE product lineup with real photos.",prod_cta_tag:"NEED HELP CHOOSING?",prod_cta_title:"The right product for your store — we'll advise you directly.",prod_cta_desc:"With 20 years of expertise, we recommend the optimal product for your store size, burner type, and ceiling height.",prod_cta_gallery:"View Installation Gallery",
parts_tag:"PARTS CATALOG · 50 ITEMS",parts_hero_title:"Parts",parts_hero_desc:"All the parts that make up YUSUNG ACE hoods at a glance. Check each part with real product photos.",
manual_hero_title:"User Manual",manual_hero_desc:"Proper usage and maintenance guide for YUSUNG ACE products.",
gallery_hero_tag:"CONSTRUCTION GALLERY",gallery_hero_desc:"YUSUNG ACE's charcoal grill hood lineup installed on site. Explore Galaxy series, acrylic lights, UFO hoods, external springs and more.",
process_hero_t1:"From site survey to after-service,",process_hero_t2:"4-step one-stop system.",process_hero_desc:"A specialist with 20 years of expertise visits your store to design, manufacture, and install the optimal solution.",process_tag:"OUR PROCESS",process_step1_title:"Site Survey / Consultation",process_step1_desc:"A specialist with 20 years of experience visits your store to measure dimensions, burner type, and ceiling height, then recommends the optimal hood system.",process_step2_title:"Custom Design & Quote",process_step2_desc:"We recommend the best Galaxy A–D model for your store and provide drawings and a transparent quote, considering ceiling height, burner layout, and foot traffic.",process_step3_title:"In-House Manufacturing",process_step3_desc:"Precision-built at our own YUSUNG ACE factory and shipped directly to your site. Every screw is 100% domestically produced — quality we stand behind.",process_step4_title:"Installation & After-Service",process_step4_desc:"Professional technician installation + F.V.D fire damper inspection + patented parts A/S support. A one-stop service that takes responsibility even after installation.",process_cta:"Request Free Site Survey",process_cta_text:"Get a consultation right now",process_cta_btn:"Request Quote",
tech_hero_tag:"TECHNOLOGY DEEP DIVE",tech_hero_t1:"8 core technologies,",tech_hero_t2:"inside one hood.",tech_hero_desc:"YUSUNG ACE, walking a single path for 20 years, unveils all core technologies designed in-house and proven on-site.",tech_tag:"CORE TECHNOLOGY",tech_title:"YUSUNG ACE's Core Technology",tech_impact:"Designed and manufactured in our own factory.",tech_3d_title:"3D Hood System",tech_stat1_label:"Patented Tech",tech_stat1_val:"5+",tech_stat2_label:"Model Lineup",tech_stat2_val:"148",tech_stat3_label:"Coverage",tech_stat3_val:"Nationwide",tech_stat4_label:"Experience",tech_stat4_val:"20 yrs",
footer_company:"YUSUNG ACE Co., Ltd.",footer_desc:"Korea's No.1 Duct — A charcoal grill hood specialist since 2007. Staying one step ahead with new environments and new technology.",footer_addr:"103, Central Sandan 1-ro, Paju-eup, Paju-si, Gyeonggi-do",footer_addr_label:"Address",footer_tel:"TEL",footer_fax:"FAX",footer_ceo:"CEO",footer_ceo_name:"Jinseon Park",footer_biz:"Business Reg. No.",footer_rights:"All rights reserved.",footer_no1:"Korea's No.1 Duct",
lang_ko:"한국어",lang_en:"English",lang_ja:"日本語",lang_vi:"Tiếng Việt",lang_zh:"中文",
nav_about_ceo:"CEO Message",nav_about_ceo_sub:"The promise of YUSUNG ACE",nav_about_map:"Directions",nav_about_map_sub:"Head office & factory location",
mega_cat1:"Galaxy A~D Type",mega_cat1_sub:"Swing spring/FVD/grease filter integrated",mega_cat2:"Side Spring BEST",mega_cat2_sub:"Side spring swing series",mega_cat3:"LED Lighting / UFO",mega_cat3_sub:"LED/Halogen lights & acrylic lights",mega_cat4:"Pipe / Spiral",mega_cat4_sub:"Stainless pipe (plated/painted) · Spiral",mega_cat5:"Fresh Ball / Flex Duct",mega_cat5_sub:"Flexible connection ducts",mega_view_all:"View All →",
cta_tag:"SINCE 2007 · PROVEN QUALITY",cta_title1:"Once you try it,",cta_title2:"there's no going back.",cta_desc:"The quality difference that grew through word-of-mouth alone — experience it yourself.",cta_btn_products:"View Product Lineup",cta_btn_inquiry:"Request Quote",
core_title:"Advantages of YUSUNG ACE Hoods.",core_desc:"A new wave in charcoal grill duct systems. Improved convenience with hygiene, safety, and visual beauty all in one.",core_label_upper:"Upper Pipe",core_label_fvd:"Fire Damper",core_label_lower:"Lower Pipe",core_label_cap:"Bell Cap Grease Catcher",core_tagline:"Technology that bends but never breaks",
core_f1_title:"01 360° Swing at Table Level",core_f1_desc:"The pipe rotates 360° in a pendulum motion from the vertical axis, eliminating breakage concerns.",core_f2_title:"02 Easy Interior Cleaning",core_f2_desc:"The lower pipe detaches easily, allowing anyone to clean the pipe interior effortlessly.",core_f3_title:"03 Safety & Maintenance Options",core_f4_title:"04 Custom Manufacturing",core_f4_desc:"Custom lengths available. Standard L1800 base can be cut or extended to fit various sites.",
impact_copy:"Korea's technology, YUSUNG ACE, reaching the world.",stat_products:"Product Lineup",stat_engineering:"Engineering",stat_swing:"Swing System",stat_domestic:"Made in Korea",
about_ceo_name:"Jinseon Park",about_ceo_p1:"YUSUNG ACE is a leader in ventilation solutions that brings the value of the field to life through technology. Since our founding, we have led innovation in kitchen ventilation systems based on field-centered technology and customer-first values.",about_ceo_p2:"From design to manufacturing and on-site installation, the precision of not missing a single screw or bolt is the pride YUSUNG ACE has upheld. As a domestic manufacturer, we have grown alongside our clients as a partner that resolves the countless variables and challenges encountered in the field.",about_ceo_p3:"All YUSUNG ACE products are designed with user-centered principles that maximize convenience. We listen to the voices of those who handle equipment in real-world settings, and our mission is to create safer and more efficient ventilation environments.",about_ceo_p4:"Going forward, YUSUNG ACE promises to provide the finest ventilation solutions through relentless R&D and rigorous quality control, leading Korea's kitchen ventilation culture. We extend our sincere gratitude to our customers for their unwavering trust and support.",
about_addr1:"103, Central Sandan 1-ro, Paju-eup, Paju-si, Gyeonggi-do",about_addr2:"(Bongam-ri 1371-9)",about_ci_name:"YUSUNG ACE",about_ci_ceo:"Jinseon Park",
form_name:"Name",form_phone:"Phone",form_company:"Company / Store Name",form_type:"Inquiry Type",form_type_quote:"Quote",form_type_install:"Installation",form_type_as:"A/S",form_type_other:"Other",form_content:"Message",form_phone_alt:"Or call 1588-9123",form_new_inquiry:"New Inquiry",
prod_stat1:"11 Categories",prod_stat2:"148 Real Photos",prod_stat3:"20 Years of Expertise",prod_no_items:"No products in this category.",prod_filter_all:"All",prod_cta_t1:"By Store Type",prod_cta_t2:"Customized Lineup.",prod_parts_t1:"148 products,",prod_parts_t2:"one standard parts system.",prod_consult_t1:"The right model for your store,",prod_consult_t2:"we'll help you choose.",prod_consult_desc:"With 20 years of expertise, we recommend the optimal line for your store size, menu, and interior.",prod_consult_phone:"Call 1588-9123",prod_consult_about:"Company Info",
manual_f1_title:"Grease Guide Device (Inner Catcher)",manual_f1_desc:"Zero grease dripping during use. The integrated grease catcher safely collects oil inside the hood.",manual_f1_tag:"ZERO Grease Drip",manual_f2_title:"Silent Suction Design",manual_f2_desc:"No whistling noise even with strong air pressure. Precision airflow design maintains a comfortable environment.",manual_f2_tag:"Powerful & Silent",manual_f3_title:"Screw-Type Easy Disassembly",manual_f3_desc:"The pipe ring uses screw-type assembly for easy disassembly and interior cleaning by anyone.",manual_f3_tag:"Tool-Free Disassembly",manual_f4_title:"Grease Filter",manual_f4_desc:"Filters grease to keep motor and duct interior clean. Extends motor life and prevents fire.",manual_f4_tag:"Motor Life + Fire Prevention",manual_f5_title:"360° Free Swing",manual_f5_desc:"The pipe swings freely like a pendulum with zero risk of breakage, usable from any angle at the table.",manual_f5_tag1:"ZERO Pipe Breakage",manual_f5_tag2:"360° Rotation",manual_f5_tag3:"Pendulum Principle",manual_video_link:"Watch Official Video",
gallery_hero_t1:"20 years of installations,",gallery_hero_t2:"found all across Korea.",gallery_source:"Photos: usungace.com official portfolio · Click for details",gallery_modal_desc:"Description",gallery_modal_features:"Key Features",gallery_modal_spec:"Specifications",gallery_modal_tags:"Tags",
tech_hero_desc2:"YUSUNG ACE, walking a single path for 20 years, unveils all core technologies designed in-house and proven on-site.",
notice_tag:"NOTICE",notice_title:"YUSUNG ACE News",notice_desc:"Check important notices, A/S schedules, and event news in one place.",
board_tag:"BOARD",board_title:"Board",board_desc:"Tech info, project cases, and product news blog-style.",board_sort_latest:"Latest",board_sort_views:"Most Viewed",board_sort_num:"By Number",board_col_no:"No.",board_col_cat:"Category",board_col_title:"Title",board_col_author:"Author",board_col_date:"Date",board_col_views:"Views",
archive_tag:"ARCHIVE",archive_title:"Archive",archive_desc:"Check patents, design registrations, and certifications held by YUSUNG ACE.",archive_all:"All Documents",archive_filter_patent:"Patents",archive_filter_design:"Design Reg.",archive_filter_cert:"Certificates",archive_stat_patent:"Patents",archive_stat_design:"Design Reg.",archive_stat_cert:"Certificates",archive_stat_knowhow:"Technical Know-how",
footer_copyright:"© 2026 YUSUNG ACE. All rights reserved.",
mega_categories:"CATEGORIES",mega_full_list:"FULL PRODUCT LIST",mega_filtered:"FILTERED"
},

ja:{
nav_home:"ホーム",nav_about:"会社紹介",nav_products:"製品紹介",nav_parts:"部品紹介",nav_gallery:"施工ギャラリー",nav_tech:"技術",nav_manual:"使い方",nav_customer:"お客様センター",nav_notice:"お知らせ",nav_board:"掲示板",nav_archive:"資料室",nav_inquiry:"施工事例 / 見積相談",nav_contact:"Contact Us",nav_core_tech:"コア技術",nav_process:"プロセス",nav_core_desc:"360°スイング、簡単清掃、FVD防火ダンパー、オーダーメイド",nav_process_desc:"現場実測から施工・アフターサービスまで4段階",nav_manual_desc:"製品の設置・メンテナンス ビジュアルガイド",nav_notice_desc:"重要なお知らせ・イベント情報",nav_board_desc:"技術情報、施工事例、製品ニュース",nav_archive_desc:"特許、認証書など",nav_inquiry_desc:"店舗規模別オーダーメイド設計",
hero_tag:"SINCE 2007 · YUSUNG ACE",hero_title1:"韓国のダクト",hero_title2:"No.1",hero_sub:"今日を動かす原動力。",hero_scroll1a:"新しい環境、新しい技術で",hero_scroll1b:"一歩先を行きます。",hero_scroll2a:"信頼と分かち合いの中で",hero_scroll2b:"愛される企業へ。",
feat1_title:"360°スイング",feat1_desc:"振り子のように360°自由回転。パイプが固定されていないため、折れる心配なく便利です。",feat2_title:"F.V.D 防火ダンパー",feat2_desc:"風速調節兼用の防火ダンパーで火災時に自動遮断。200〜220℃で閉じて火災の拡大を防ぎます。",feat3_title:"分離清掃可能",feat3_desc:"工具不要で手で分離。毎日洗浄可能な衛生構造。ワンタッチで上部パイプも清掃可能。",feat4_title:"上下作動テンション",feat4_desc:"ベアリング張力調整＋ストップバーブレーキで安全な高さ調節。オーダーメイドも可能です。",
fim_tag:"FEATURES IN MOTION",fim_title_a:"ディテールを",fim_title_b:"動きで",fim_title_c:"ご確認ください。",fim_desc:"4つのコア技術が実際にどう動くのか、見ているだけで実感できます。",fim_card1_tag:"01 / SWING",fim_card1_title:"360°フリースイング",fim_card1_desc:"テンションネジ方式で上下左右360°完全自由回転。プレートが動いてもパイプは定位置を保ちます。",fim_card2_tag:"02 / CLEAN",fim_card2_title:"ワンタッチ分離清掃",fim_card2_desc:"ネジ一回転で上部パイプまで丸ごと分離。内部の油汚れを直接確認しながら毎日洗浄可能です。",fim_card3_tag:"03 / SAFETY",fim_card3_title:"安全・メンテナンスオプション",fim_card3_desc:"FVD防火ダンパー: 200〜220℃でダンパーが閉じて火災を予防。ワンタッチで上部パイプも清掃可能。",fim_card4_tag:"04 / CUSTOM",fim_card4_title:"オーダーメイド製作",fim_card4_desc:"ご希望の長さでオーダーメイド可能。基本仕様L1800基準で切断・延長できます。",
www_tag:"WHERE WE WORK",www_title_a:"韓国の",www_title_b:"炎の現場で",www_title_c:"。",www_desc:"フランチャイズの厨房から過酷な製造現場、精密な研究所まで。ユソンエースは毎日、数多くの専門家の作業環境を快適に守っています。",www_case1_tag:"USE CASE 01",www_case1_title:"直火焼肉店",www_case1_desc:"各テーブルの油跳ねを防止し、360°スイングで自由に煙を吸引。",www_case1_btn:"パイプシリーズを見る",www_case2_tag:"USE CASE 02",www_case2_title:"大型フランチャイズ",www_case2_desc:"全店舗統一規格・部品交換の標準化。F.V.D防火ダンパーで多店舗の安全を一括管理。",www_case2_btn:"LED照明を見る",www_case3_tag:"USE CASE 03",www_case3_title:"工場 / 研究室",www_case3_desc:"煙が充満する現場でも、精密な換気が必要な研究室でも、換気ソリューションを提供します。",www_case3_btn:"フレッシュボール笠ジャバラを見る",www_cta_text:"お店にどのモデルが合うかわからない？",www_cta_btn:"無料相談申し込み",
stmt_tag:"A NEW STANDARD",stmt_title1:"新時代のユソンエース、",stmt_title2:"飲食店の未来",stmt_title3:"を切り拓く。",stmt_desc:"直火グリルダクト設備の流れが変わる時代。心血を注いで完成させたユソンエースならではの独自技術力をご覧ください。",stmt_chip1:"360° SWING",stmt_chip2:"F.V.D 防火ダンパー",stmt_chip3:"分離清掃",stmt_chip4:"上下テンション",stmt_chip5:"エコ設計",
gp_tag:"REAL CONSTRUCTION",gp_title1:"20年間積み重ねた",gp_title2:"リアルな現場写真。",gp_btn:"全ギャラリーを見る",
vid_tag:"YUSUNG ACE IN ACTION",vid_title1:"ユソンエースフード、",vid_title2:"動く姿そのまま。",vid_desc:"360°スイング、上下テンション、FVD防火ダンパーの動作を映像でご覧ください。20年のノウハウが生んだ滑らかで正確な動き。",vid_btn:"Naverブログで映像を見る",
about_hero_tag:"SINCE 2007 · ABOUT US",about_hero_t1:"信頼と分かち合いの中で",about_hero_t2:"愛される企業へ。",about_hero_desc:"業界をリードする革新の出発点、その中心には常にユソンエースがあります。速度ではなく正しい方向で築いた独自の基準は、真似のできない誇りとなり、お客様の信頼にお応えします。",about_ceo_tag:"CEO MESSAGE",about_ceo_label:"代表取締役",about_ci_tag:"COMPANY INFO",about_ci_title:"会社情報",about_ci_ceo_title:"代表取締役",about_ci_biz_label:"事業者登録番号",about_loc_tag:"LOCATION",about_loc_title:"アクセス",about_naver_map:"Naverマップ",about_kakao_map:"Kakaoマップ",about_promise_tag:"OUR PROMISE",about_promise_t1:"最高の技術と品質で",about_promise_t2:"サービスによるお客様満足の実現。",about_promise_desc:"環境にやさしい都市開発をリードする企業、ユソンエースは2007年から一筋の道を歩んできた韓国ダクトNo.1です。",about_contact_tag:"CONTACT US",about_contact_title:"お問い合わせ",about_contact_desc:"見積、設置、A/Sなどご不明な点がございましたらお気軽にお問い合わせください。",about_form_submit:"お問い合わせ送信",about_success_title:"お問い合わせを受け付けました！",about_success_desc:"担当者より早急にご連絡いたします。",
prod_hero_tag:"PRODUCT LINEUP · 148 MODELS",prod_hero_t1:"148種の製品、",prod_hero_t2:"ひとつの職人精神。",prod_hero_desc:"ギャラクシーA·B·C·Dタイプ、両側ゼンマイ、LED照明、LEDスペースシップ、スパイラル、パイプ、フレッシュボールまで — ユソンエースの全製品ラインナップを実写真でご覧ください。",prod_cta_tag:"NEED HELP CHOOSING?",prod_cta_title:"お店に合った製品、直接ご相談いたします。",prod_cta_desc:"20年のノウハウで店舗規模・火炉の種類・天井高に合った最適な製品をご提案します。",prod_cta_gallery:"施工ギャラリーを見る",
parts_tag:"PARTS CATALOG · 50 ITEMS",parts_hero_title:"部品紹介",parts_hero_desc:"ユソンエースフードを構成するすべての部品を一覧で。各部品の実物写真でご確認ください。",
manual_hero_title:"使い方",manual_hero_desc:"ユソンエース製品の正しい使用方法とメンテナンスガイドです。",
gallery_hero_tag:"CONSTRUCTION GALLERY",gallery_hero_desc:"ユソンエースが施工した直火器フードラインナップ。ギャラクシーシリーズ、アクリルライト、スペースシップフード、外部ゼンマイなど多彩な現場写真をご覧ください。",
process_hero_t1:"現場実測からアフターサービスまで、",process_hero_t2:"4段階ワンストップシステム。",process_hero_desc:"20年のノウハウを持つ専門家が直接訪問し、お店に最適なソリューションを設計・製作・施工します。",process_tag:"OUR PROCESS",process_step1_title:"現場実測 / 相談",process_step1_desc:"20年のノウハウを持つ専門家が直接訪問し、店舗規模・火炉の種類・天井高を測定。現場環境に最適なフードシステムをご提案します。",process_step2_title:"オーダーメイド設計・見積",process_step2_desc:"ギャラクシーA〜Dの中から最適モデルを推薦し、図面・見積書をご提供。天井高、火炉配置、動線すべてを考慮したオーダーメイド設計です。",process_step3_title:"自社工場製作",process_step3_desc:"ユソンエース自社工場で精密製作後、現場へ直接配送。ネジ一本まで100%国内自社生産、品質への誇りです。",process_step4_title:"施工・アフターサービス",process_step4_desc:"専門技術者による施工 + F.V.D防火ダンパー点検 + 特許部品A/Sサポート。施工後もメンテナンスまで責任を持つワンストップサービスです。",process_cta:"無料現場実測を申し込む",process_cta_text:"今すぐご相談ください",process_cta_btn:"見積相談",
tech_hero_tag:"TECHNOLOGY DEEP DIVE",tech_hero_t1:"8つのコア技術、",tech_hero_t2:"ひとつのフードの中に。",tech_hero_desc:"20年間ひとつの道を歩んできたユソンエースが自ら設計し、現場で実証したコア技術をすべて公開します。",tech_tag:"CORE TECHNOLOGY",tech_title:"ユソンエース独自のコア技術",tech_impact:"自社工場で直接設計・生産しています。",tech_3d_title:"3Dフードシステム",tech_stat1_label:"特許技術",tech_stat1_val:"5件+",tech_stat2_label:"モデルラインナップ",tech_stat2_val:"148種",tech_stat3_label:"施工実績",tech_stat3_val:"全国",tech_stat4_label:"業歴",tech_stat4_val:"20年",
footer_company:"株式会社 ユソンエース",footer_desc:"韓国ダクトNo.1 — 2007年から一筋の道を歩む直火器フード専門企業。新しい環境、新しい技術で一歩先を行きます。",footer_addr:"京畿道パジュ市パジュ邑セントラル産団1路103",footer_addr_label:"住所",footer_tel:"TEL",footer_fax:"FAX",footer_ceo:"代表",footer_ceo_name:"パク・ジンソン",footer_biz:"事業者登録番号",footer_rights:"All rights reserved.",footer_no1:"韓国ダクトNo.1",
lang_ko:"한국어",lang_en:"English",lang_ja:"日本語",lang_vi:"Tiếng Việt",lang_zh:"中文",
nav_about_ceo:"CEO挨拶",nav_about_ceo_sub:"ユソンエースの約束",nav_about_map:"アクセス",nav_about_map_sub:"本社・工場の所在地",
mega_cat1:"ギャラクシー A~Dタイプ",mega_cat1_sub:"スイングゼンマイ/FVD/油脂フィルター統合",mega_cat2:"両側ゼンマイ BEST",mega_cat2_sub:"両側ゼンマイスイングシリーズ",mega_cat3:"LED照明 / スペースシップ",mega_cat3_sub:"LED/ハロゲンライト&アクリルライト",mega_cat4:"パイプ / スパイラル",mega_cat4_sub:"ステンレスパイプ（メッキ/塗装）· スパイラル",mega_cat5:"フレッシュボール / フレキシブル管",mega_cat5_sub:"フレキシブル接続管",mega_view_all:"すべて見る →",
cta_tag:"SINCE 2007 · PROVEN QUALITY",cta_title1:"一度使うと、",cta_title2:"もう戻れません。",cta_desc:"マーケティングなしに口コミだけで成長した品質の違い、ぜひ体験してください。",cta_btn_products:"製品ラインナップ",cta_btn_inquiry:"見積依頼",
core_title:"ユソンエースフードの利点。",core_desc:"直火器ダクト設備の新しい流れ。不便を改善し、衛生・安全・美しさをすべて実現しました。",core_label_upper:"上部パイプ",core_label_fvd:"防火ダンパー",core_label_lower:"下部パイプ",core_label_cap:"ラッパキャップ油受け",core_tagline:"揺れても折れない技術力",
core_f1_title:"01 テーブル基準360°スイング",core_f1_desc:"パイプが固定されず、垂直から振り子のように360°回転し、折れる心配がありません。",core_f2_title:"02 簡単な内部清掃",core_f2_desc:"下部パイプを簡単に分離でき、誰でも手軽にパイプ内部の清掃が可能です。",core_f3_title:"03 安全・メンテナンスオプション",core_f4_title:"04 オーダーメイド製作",core_f4_desc:"ご希望の長さでオーダーメイド可能。基本仕様L1800基準で切断・延長できます。",
impact_copy:"韓国の技術ユソンエース、世界へ。",stat_products:"製品ラインナップ",stat_engineering:"エンジニアリング",stat_swing:"スイングシステム",stat_domestic:"国内製造",
about_ceo_name:"パク・ジンソン",about_ceo_p1:"現場の価値を技術で実現する換気ソリューションのリーダー、ユソンエースです。創立以来「現場中心の技術力」と「顧客最優先の価値」を基に厨房換気システムの革新を牽引してきました。",about_ceo_p2:"設計から製造、実際の現場施工に至るまで、ネジ一本のディテールも見逃さない精巧さはユソンエースの誇りです。国内直接生産メーカーとして、現場で発生する変数や課題を解決する「パートナー」としてお客様と共に成長してきました。",about_ceo_p3:"ユソンエースのすべての製品は、ユーザーの利便性を最大化したユーザー中心設計を追求しています。現場で機器を扱う方々の声に耳を傾け、より安全で効率的な換気環境を作ることが私たちの使命です。",about_ceo_p4:"今後もユソンエースは絶え間ない研究開発と徹底した品質管理を通じて、韓国の厨房換気文化をリードする最高の換気ソリューションを提供することをお約束します。変わらぬご信頼とご支援をいただいているお客様に心より感謝申し上げます。",
about_addr1:"京畿道パジュ市パジュ邑セントラル産団1路103",about_addr2:"(ポンアムリ1371-9)",about_ci_name:"ユソンエース",about_ci_ceo:"パク・ジンソン",
form_name:"お名前",form_phone:"連絡先",form_company:"会社名 / 店舗名",form_type:"お問い合わせ種別",form_type_quote:"見積依頼",form_type_install:"設置相談",form_type_as:"A/S相談",form_type_other:"その他",form_content:"お問い合わせ内容",form_phone_alt:"または 1588-9123 にお電話ください",form_new_inquiry:"新規お問い合わせ",
prod_stat1:"11カテゴリ",prod_stat2:"148種の実写真",prod_stat3:"20年の技術ノウハウ",prod_no_items:"該当カテゴリの製品がありません。",prod_filter_all:"すべて",prod_cta_t1:"店舗タイプ別",prod_cta_t2:"カスタムラインナップ。",prod_parts_t1:"148種の製品、",prod_parts_t2:"ひとつの標準部品。",prod_consult_t1:"お店に合うモデル、",prod_consult_t2:"一緒にお選びします。",prod_consult_desc:"20年のノウハウで店舗規模、メニュー、インテリアに合った最適ラインをご提案します。",prod_consult_phone:"1588-9123 電話相談",prod_consult_about:"会社情報を見る",
manual_f1_title:"油誘導装置（油受け内蔵）",manual_f1_desc:"使用中に油が全く垂れません。一体成形の油受けがフード内部の油を安全に集めて衛生的に管理します。",manual_f1_tag:"油垂れZERO",manual_f2_title:"無音吸引設計",manual_f2_desc:"吸引口の気圧が強くても笛音がしません。精密なエアフロー設計で店内の快適な環境を維持します。",manual_f2_tag:"静音強力吸引",manual_f3_title:"ネジタイプ簡単分離",manual_f3_desc:"上下を連結するパイプリングがネジタイプで組み立てられ、分離が簡単で内部清掃が可能です。",manual_f3_tag:"工具不要の簡単分離",manual_f4_title:"油脂フィルター",manual_f4_desc:"油脂を濾過してモーターとダクト内部を清潔に保ちます。モーター寿命の延長と火災予防の二重効果。",manual_f4_tag:"モーター寿命延長+火災予防",manual_f5_title:"360°フリースイング",manual_f5_desc:"パイプが固定されず自由にスイングします。振り子のように滑らかに回転し折れる心配なし。テーブル基準でどこからでも自由に使えます。",manual_f5_tag1:"パイプ破損ZERO",manual_f5_tag2:"360°回転",manual_f5_tag3:"振り子原理",manual_video_link:"ユソンエース公式映像を見る",
gallery_hero_t1:"20年の施工、",gallery_hero_t2:"全国各地にあります。",gallery_source:"写真出典: usungace.com公式ポートフォリオ · 写真クリックで詳細",gallery_modal_desc:"説明",gallery_modal_features:"主な特徴",gallery_modal_spec:"製品仕様",gallery_modal_tags:"タグ",
tech_hero_desc2:"20年間ひとつの道を歩んできたユソンエースが自ら設計し、現場で実証したコア技術をすべて公開します。",
notice_tag:"NOTICE · お知らせ",notice_title:"ユソンエースニュース",notice_desc:"重要なお知らせ、A/Sスケジュール、イベント情報を一箇所で確認。",
board_tag:"BOARD · 掲示板",board_title:"掲示板",board_desc:"ユソンエースの技術情報、施工事例、製品ニュースをブログ形式で。",board_sort_latest:"最新順",board_sort_views:"閲覧順",board_sort_num:"番号順",board_col_no:"番号",board_col_cat:"分類",board_col_title:"タイトル",board_col_author:"作成者",board_col_date:"登録日",board_col_views:"閲覧",
archive_tag:"ARCHIVE · 資料室",archive_title:"資料室",archive_desc:"ユソンエースが保有する特許、デザイン登録、認証書を確認。",archive_all:"全資料",archive_filter_patent:"特許",archive_filter_design:"デザイン登録",archive_filter_cert:"認証書",archive_stat_patent:"特許保有",archive_stat_design:"デザイン登録",archive_stat_cert:"認証書",archive_stat_knowhow:"技術ノウハウ",
footer_copyright:"© 2026 YUSUNG ACE / ユソンエース. All rights reserved.",
mega_categories:"カテゴリ",mega_full_list:"全製品リスト",mega_filtered:"フィルター結果"
},

vi:{
nav_home:"Trang chủ",nav_about:"Giới thiệu",nav_products:"Sản phẩm",nav_parts:"Linh kiện",nav_gallery:"Công trình",nav_tech:"Công nghệ",nav_manual:"Hướng dẫn",nav_customer:"Hỗ trợ",nav_notice:"Thông báo",nav_board:"Diễn đàn",nav_archive:"Tài liệu",nav_inquiry:"Công trình / Báo giá",nav_contact:"Liên hệ",nav_core_tech:"Công nghệ lõi",nav_process:"Quy trình",nav_core_desc:"Xoay 360°, Vệ sinh dễ dàng, Van chống cháy FVD, Sản xuất theo yêu cầu",nav_process_desc:"4 bước từ khảo sát đến bảo trì sau lắp đặt",nav_manual_desc:"Hướng dẫn trực quan lắp đặt & bảo trì",nav_notice_desc:"Thông báo quan trọng và sự kiện",nav_board_desc:"Thông tin kỹ thuật, công trình, tin sản phẩm",nav_archive_desc:"Bằng sáng chế, chứng nhận, v.v.",nav_inquiry_desc:"Thiết kế tùy chỉnh theo quy mô cửa hàng",
hero_tag:"SINCE 2007 · YUSUNG ACE",hero_title1:"Ống gió Hàn Quốc",hero_title2:"No.1",hero_sub:"Động lực dẫn đầu hôm nay.",hero_scroll1a:"Với môi trường mới, công nghệ mới,",hero_scroll1b:"chúng tôi luôn đi trước một bước.",hero_scroll2a:"Trong niềm tin và sẻ chia,",hero_scroll2b:"trở thành doanh nghiệp được yêu mến.",
feat1_title:"Xoay 360°",feat1_desc:"Xoay tự do 360° như con lắc. Ống không cố định nên không lo gãy, sử dụng tiện lợi.",feat2_title:"Van chống cháy F.V.D",feat2_desc:"Van chống cháy kiêm điều chỉnh tốc độ gió, tự động đóng khi có hỏa hoạn. Đóng ở 200–220°C ngăn lửa lan.",feat3_title:"Tháo rời vệ sinh",feat3_desc:"Tháo bằng tay không cần dụng cụ. Kết cấu vệ sinh cho phép rửa hàng ngày. Tháo nhanh cả ống phía trên.",feat4_title:"Điều chỉnh lực căng",feat4_desc:"Điều chỉnh lực căng ổ bi + phanh thanh chặn giúp điều chỉnh chiều cao an toàn. Có thể sản xuất theo chiều dài tùy chỉnh.",
fim_tag:"FEATURES IN MOTION",fim_title_a:"Xem ",fim_title_b:"chi tiết",fim_title_c:" qua chuyển động.",fim_desc:"Hãy quan sát 4 công nghệ cốt lõi vận hành thực tế — chỉ cần nhìn cũng cảm nhận được.",fim_card1_tag:"01 / SWING",fim_card1_title:"Xoay tự do 360°",fim_card1_desc:"Cơ chế vít lực căng cho phép xoay tự do 360° mọi hướng. Đĩa di chuyển nhưng ống luôn giữ nguyên vị trí.",fim_card2_tag:"02 / CLEAN",fim_card2_title:"Tháo rời một chạm",fim_card2_desc:"Chỉ một vòng vít là tháo toàn bộ ống phía trên. Kiểm tra và rửa dầu mỡ bên trong mỗi ngày.",fim_card3_tag:"03 / SAFETY",fim_card3_title:"An toàn & Bảo trì",fim_card3_desc:"Van chống cháy FVD: đóng ở 200–220°C ngăn cháy lan. Tháo nhanh để vệ sinh ống phía trên.",fim_card4_tag:"04 / CUSTOM",fim_card4_title:"Sản xuất theo yêu cầu",fim_card4_desc:"Sản xuất theo đúng chiều dài bạn cần. Tiêu chuẩn L1800, có thể cắt hoặc nối dài.",
www_tag:"WHERE WE WORK",www_title_a:"Trước ",www_title_b:"ngọn lửa",www_title_c:" Hàn Quốc.",www_desc:"Từ bếp nhượng quyền đến nhà máy sản xuất khắc nghiệt và phòng thí nghiệm chính xác — YUSUNG ACE giữ cho môi trường làm việc của vô số chuyên gia luôn trong lành mỗi ngày.",www_case1_tag:"USE CASE 01",www_case1_title:"Quán thịt nướng",www_case1_desc:"Ngăn dầu mỡ rơi từng bàn, hút khói tự do 360° với cơ chế xoay.",www_case1_btn:"Xem dòng ống Pipe",www_case2_tag:"USE CASE 02",www_case2_title:"Nhượng quyền lớn",www_case2_desc:"Quy cách thống nhất toàn chuỗi, thay thế linh kiện tiêu chuẩn hóa. Van chống cháy F.V.D quản lý an toàn đồng loạt.",www_case2_btn:"Xem đèn LED",www_case3_tag:"USE CASE 03",www_case3_title:"Nhà máy / Phòng thí nghiệm",www_case3_desc:"Giải pháp thông gió cho cả nhà máy đầy khói lẫn phòng thí nghiệm cần thông gió chính xác.",www_case3_btn:"Xem Fresh Ball chụp mềm",www_cta_text:"Chưa biết model nào phù hợp cửa hàng?",www_cta_btn:"Tư vấn miễn phí",
stmt_tag:"A NEW STANDARD",stmt_title1:"YUSUNG ACE thế hệ mới,",stmt_title2:"tương lai nhà hàng",stmt_title3:" đã đến.",stmt_desc:"Trong thời đại hệ thống ống gió bếp nướng đang thay đổi, hãy khám phá công nghệ độc quyền mà YUSUNG ACE dày công hoàn thiện.",stmt_chip1:"360° SWING",stmt_chip2:"Van chống cháy F.V.D",stmt_chip3:"Vệ sinh tháo rời",stmt_chip4:"Lực căng điều chỉnh",stmt_chip5:"Thiết kế xanh",
gp_tag:"REAL CONSTRUCTION",gp_title1:"20 năm tích lũy",gp_title2:"ảnh công trình thực tế.",gp_btn:"Xem toàn bộ",
vid_tag:"YUSUNG ACE IN ACTION",vid_title1:"Chụp hút YUSUNG ACE,",vid_title2:"xem chuyển động thực tế.",vid_desc:"Xem 360° xoay, lực căng điều chỉnh, van chống cháy FVD hoạt động. Chuyển động mượt mà và chính xác từ 20 năm kinh nghiệm.",vid_btn:"Xem trên Naver Blog",
about_hero_tag:"SINCE 2007 · ABOUT US",about_hero_t1:"Trong niềm tin và sẻ chia,",about_hero_t2:"trở thành doanh nghiệp được yêu mến.",about_hero_desc:"Ở trung tâm đổi mới dẫn đầu ngành luôn có YUSUNG ACE. Tiêu chuẩn được xây dựng theo hướng đúng chứ không phải tốc độ đã trở thành niềm tự hào không thể sao chép, đáp lại sự tin tưởng của khách hàng.",about_ceo_tag:"CEO MESSAGE",about_ceo_label:"Giám đốc",about_ci_tag:"COMPANY INFO",about_ci_title:"Thông tin công ty",about_ci_ceo_title:"Giám đốc",about_ci_biz_label:"Mã số doanh nghiệp",about_loc_tag:"LOCATION",about_loc_title:"Đường đi",about_naver_map:"Naver Map",about_kakao_map:"Kakao Map",about_promise_tag:"OUR PROMISE",about_promise_t1:"Với công nghệ và chất lượng hàng đầu,",about_promise_t2:"hiện thực hóa sự hài lòng qua dịch vụ.",about_promise_desc:"Dẫn đầu phát triển đô thị xanh, YUSUNG ACE là nhà sản xuất ống gió No.1 Hàn Quốc từ 2007.",about_contact_tag:"CONTACT US",about_contact_title:"Liên hệ",about_contact_desc:"Để lại câu hỏi về báo giá, lắp đặt hoặc bảo hành, chúng tôi sẽ phản hồi sớm nhất.",about_form_submit:"Gửi yêu cầu",about_success_title:"Yêu cầu đã được tiếp nhận!",about_success_desc:"Nhân viên phụ trách sẽ liên hệ bạn sớm.",
prod_hero_tag:"PRODUCT LINEUP · 148 MODELS",prod_hero_t1:"148 sản phẩm,",prod_hero_t2:"một tinh thần thợ lành nghề.",prod_hero_desc:"Galaxy A·B·C·D, lò xo hai bên, đèn LED, UFO LED, xoắn ốc, ống, quả cầu tươi — xem toàn bộ dòng sản phẩm YUSUNG ACE với ảnh thực tế.",prod_cta_tag:"NEED HELP CHOOSING?",prod_cta_title:"Sản phẩm phù hợp cửa hàng — tư vấn trực tiếp.",prod_cta_desc:"Với 20 năm kinh nghiệm, chúng tôi đề xuất sản phẩm tối ưu cho quy mô, loại bếp và chiều cao trần cửa hàng.",prod_cta_gallery:"Xem công trình thi công",
parts_tag:"PARTS CATALOG · 50 ITEMS",parts_hero_title:"Linh kiện",parts_hero_desc:"Tất cả linh kiện cấu thành chụp hút YUSUNG ACE. Xem ảnh thực tế từng linh kiện.",
manual_hero_title:"Hướng dẫn sử dụng",manual_hero_desc:"Hướng dẫn sử dụng đúng cách và bảo trì sản phẩm YUSUNG ACE.",
gallery_hero_tag:"CONSTRUCTION GALLERY",gallery_hero_desc:"Dòng chụp hút bếp nướng YUSUNG ACE đã lắp đặt. Khám phá Galaxy series, đèn acrylic, chụp UFO, lò xo ngoài và nhiều hơn nữa.",
process_hero_t1:"Từ khảo sát đến bảo trì,",process_hero_t2:"hệ thống trọn gói 4 bước.",process_hero_desc:"Chuyên gia 20 năm kinh nghiệm trực tiếp đến cửa hàng để thiết kế, sản xuất và lắp đặt giải pháp tối ưu.",process_tag:"OUR PROCESS",process_step1_title:"Khảo sát / Tư vấn",process_step1_desc:"Chuyên gia 20 năm kinh nghiệm trực tiếp khảo sát quy mô cửa hàng, loại bếp, chiều cao trần. Đề xuất hệ thống hút tối ưu cho môi trường thực tế.",process_step2_title:"Thiết kế & Báo giá",process_step2_desc:"Đề xuất mẫu Galaxy A–D phù hợp nhất, cung cấp bản vẽ và báo giá minh bạch. Thiết kế tùy chỉnh xét đến chiều cao trần, bố trí bếp và lối đi.",process_step3_title:"Sản xuất tại nhà máy",process_step3_desc:"Sản xuất chính xác tại nhà máy YUSUNG ACE và giao trực tiếp. Từng con ốc đều sản xuất 100% trong nước — niềm tự hào về chất lượng.",process_step4_title:"Lắp đặt & Bảo trì",process_step4_desc:"Kỹ thuật viên chuyên nghiệp lắp đặt + Kiểm tra van chống cháy F.V.D + Hỗ trợ A/S linh kiện sáng chế. Dịch vụ trọn gói chịu trách nhiệm cả sau lắp đặt.",process_cta:"Đăng ký khảo sát miễn phí",process_cta_text:"Nhận tư vấn ngay",process_cta_btn:"Yêu cầu báo giá",
tech_hero_tag:"TECHNOLOGY DEEP DIVE",tech_hero_t1:"8 công nghệ cốt lõi,",tech_hero_t2:"trong một chụp hút.",tech_hero_desc:"YUSUNG ACE, 20 năm kiên trì một con đường, công khai toàn bộ công nghệ cốt lõi tự thiết kế và kiểm chứng tại hiện trường.",tech_tag:"CORE TECHNOLOGY",tech_title:"Công nghệ cốt lõi của YUSUNG ACE",tech_impact:"Tự thiết kế và sản xuất tại nhà máy riêng.",tech_3d_title:"Hệ thống hút 3D",tech_stat1_label:"Công nghệ sáng chế",tech_stat1_val:"5+",tech_stat2_label:"Dòng sản phẩm",tech_stat2_val:"148",tech_stat3_label:"Phạm vi thi công",tech_stat3_val:"Toàn quốc",tech_stat4_label:"Kinh nghiệm",tech_stat4_val:"20 năm",
footer_company:"Công ty YUSUNG ACE",footer_desc:"Ống gió No.1 Hàn Quốc — Chuyên gia chụp hút bếp nướng từ 2007. Luôn đi trước với môi trường và công nghệ mới.",footer_addr:"103, Central Sandan 1-ro, Paju-eup, Paju-si, Gyeonggi-do",footer_addr_label:"Địa chỉ",footer_tel:"TEL",footer_fax:"FAX",footer_ceo:"Giám đốc",footer_ceo_name:"Park Jinseon",footer_biz:"Mã số doanh nghiệp",footer_rights:"All rights reserved.",footer_no1:"Ống gió No.1 Hàn Quốc",
lang_ko:"한국어",lang_en:"English",lang_ja:"日本語",lang_vi:"Tiếng Việt",lang_zh:"中文",
nav_about_ceo:"Lời chào CEO",nav_about_ceo_sub:"Cam kết của YUSUNG ACE",nav_about_map:"Đường đi",nav_about_map_sub:"Vị trí trụ sở & nhà máy",
mega_cat1:"Galaxy A~D Type",mega_cat1_sub:"Lò xo xoay/FVD/lưới lọc dầu tích hợp",mega_cat2:"Lò xo hai bên BEST",mega_cat2_sub:"Dòng lò xo xoay hai bên",mega_cat3:"Đèn LED / UFO",mega_cat3_sub:"Đèn LED/Halogen & đèn acrylic",mega_cat4:"Ống / Xoắn ốc",mega_cat4_sub:"Ống inox (mạ/sơn) · Xoắn ốc",mega_cat5:"Quả cầu tươi / Ống mềm",mega_cat5_sub:"Ống kết nối linh hoạt",mega_view_all:"Xem tất cả →",
cta_tag:"SINCE 2007 · PROVEN QUALITY",cta_title1:"Dùng một lần,",cta_title2:"không thể quay lại.",cta_desc:"Sự khác biệt chất lượng chỉ phát triển qua truyền miệng — hãy tự trải nghiệm.",cta_btn_products:"Xem sản phẩm",cta_btn_inquiry:"Yêu cầu báo giá",
core_title:"Ưu điểm của chụp hút YUSUNG ACE.",core_desc:"Xu hướng mới trong hệ thống ống gió bếp nướng. Cải thiện tiện lợi với vệ sinh, an toàn và thẩm mỹ.",core_label_upper:"Ống trên",core_label_fvd:"Van chống cháy",core_label_lower:"Ống dưới",core_label_cap:"Khay hứng dầu",core_tagline:"Công nghệ chịu lắc mà không gãy",
core_f1_title:"01 Xoay 360° tại bàn",core_f1_desc:"Ống không cố định, xoay 360° như con lắc từ trục dọc, không lo gãy.",core_f2_title:"02 Vệ sinh bên trong dễ dàng",core_f2_desc:"Ống dưới tháo dễ dàng, ai cũng có thể vệ sinh bên trong ống.",core_f3_title:"03 An toàn & Bảo trì",core_f4_title:"04 Sản xuất theo yêu cầu",core_f4_desc:"Có thể đặt theo chiều dài mong muốn. Tiêu chuẩn L1800, cắt hoặc nối dài được.",
impact_copy:"Công nghệ Hàn Quốc, YUSUNG ACE, vươn ra thế giới.",stat_products:"Sản phẩm",stat_engineering:"Kỹ thuật",stat_swing:"Hệ thống xoay",stat_domestic:"Sản xuất nội địa",
about_ceo_name:"Park Jinseon",about_ceo_p1:"YUSUNG ACE là người dẫn đầu giải pháp thông gió, hiện thực hóa giá trị hiện trường bằng công nghệ. Từ khi thành lập, chúng tôi dẫn đầu đổi mới hệ thống thông gió nhà bếp dựa trên công nghệ thực tiễn và giá trị khách hàng.",about_ceo_p2:"Từ thiết kế đến sản xuất và thi công tại hiện trường, sự chính xác không bỏ sót một con ốc là niềm tự hào của YUSUNG ACE. Là nhà sản xuất nội địa, chúng tôi đã phát triển cùng khách hàng như một đối tác giải quyết mọi thách thức tại hiện trường.",about_ceo_p3:"Tất cả sản phẩm YUSUNG ACE được thiết kế lấy người dùng làm trung tâm, tối đa hóa sự tiện lợi. Chúng tôi lắng nghe tiếng nói từ hiện trường để tạo ra môi trường thông gió an toàn và hiệu quả hơn.",about_ceo_p4:"YUSUNG ACE cam kết tiếp tục cung cấp giải pháp thông gió tốt nhất thông qua R&D không ngừng và quản lý chất lượng nghiêm ngặt. Chân thành cảm ơn sự tin tưởng và ủng hộ của quý khách.",
about_addr1:"103, Central Sandan 1-ro, Paju-eup, Paju-si, Gyeonggi-do",about_addr2:"(Bongam-ri 1371-9)",about_ci_name:"YUSUNG ACE",about_ci_ceo:"Park Jinseon",
form_name:"Họ tên",form_phone:"Số điện thoại",form_company:"Công ty / Tên cửa hàng",form_type:"Loại yêu cầu",form_type_quote:"Báo giá",form_type_install:"Lắp đặt",form_type_as:"Bảo hành",form_type_other:"Khác",form_content:"Nội dung",form_phone_alt:"Hoặc gọi 1588-9123",form_new_inquiry:"Yêu cầu mới",
prod_stat1:"11 danh mục",prod_stat2:"148 ảnh thực tế",prod_stat3:"20 năm kinh nghiệm",prod_no_items:"Không có sản phẩm trong danh mục này.",prod_filter_all:"Tất cả",prod_cta_t1:"Theo loại cửa hàng",prod_cta_t2:"Dòng sản phẩm tùy chỉnh.",prod_parts_t1:"148 sản phẩm,",prod_parts_t2:"một hệ thống linh kiện tiêu chuẩn.",prod_consult_t1:"Model phù hợp cửa hàng,",prod_consult_t2:"chúng tôi giúp bạn chọn.",prod_consult_desc:"20 năm kinh nghiệm, đề xuất dòng tối ưu cho quy mô, menu và nội thất cửa hàng.",prod_consult_phone:"Gọi 1588-9123",prod_consult_about:"Thông tin công ty",
manual_f1_title:"Thiết bị dẫn dầu (khay hứng tích hợp)",manual_f1_desc:"Hoàn toàn không rỉ dầu khi sử dụng. Khay hứng dầu tích hợp thu gom dầu bên trong chụp hút an toàn.",manual_f1_tag:"KHÔNG rỉ dầu",manual_f2_title:"Thiết kế hút im lặng",manual_f2_desc:"Không tiếng huýt gió dù áp suất hút mạnh. Thiết kế luồng khí chính xác giữ môi trường thoải mái.",manual_f2_tag:"Hút mạnh & Êm",manual_f3_title:"Tháo ren dễ dàng",manual_f3_desc:"Vòng ống kết nối kiểu ren, tháo lắp dễ dàng, ai cũng vệ sinh bên trong được.",manual_f3_tag:"Tháo không cần dụng cụ",manual_f4_title:"Lưới lọc dầu",manual_f4_desc:"Lọc dầu giữ motor và ống sạch sẽ. Kéo dài tuổi thọ motor và phòng cháy.",manual_f4_tag:"Tuổi thọ motor + Phòng cháy",manual_f5_title:"Xoay tự do 360°",manual_f5_desc:"Ống không cố định, xoay tự do như con lắc, không lo gãy. Sử dụng từ mọi góc tại bàn.",manual_f5_tag1:"KHÔNG gãy ống",manual_f5_tag2:"Xoay 360°",manual_f5_tag3:"Nguyên lý con lắc",manual_video_link:"Xem video chính thức",
gallery_hero_t1:"20 năm thi công,",gallery_hero_t2:"có mặt khắp Hàn Quốc.",gallery_source:"Ảnh: usungace.com portfolio chính thức · Nhấp ảnh xem chi tiết",gallery_modal_desc:"Mô tả",gallery_modal_features:"Đặc điểm chính",gallery_modal_spec:"Thông số",gallery_modal_tags:"Thẻ",
tech_hero_desc2:"YUSUNG ACE, 20 năm kiên trì một con đường, công khai toàn bộ công nghệ cốt lõi tự thiết kế và kiểm chứng tại hiện trường.",
notice_tag:"NOTICE · Thông báo",notice_title:"Tin YUSUNG ACE",notice_desc:"Xem thông báo quan trọng, lịch A/S và sự kiện tại đây.",
board_tag:"BOARD · Diễn đàn",board_title:"Diễn đàn",board_desc:"Thông tin kỹ thuật, công trình và tin sản phẩm YUSUNG ACE.",board_sort_latest:"Mới nhất",board_sort_views:"Xem nhiều",board_sort_num:"Theo số",board_col_no:"STT",board_col_cat:"Phân loại",board_col_title:"Tiêu đề",board_col_author:"Tác giả",board_col_date:"Ngày",board_col_views:"Lượt xem",
archive_tag:"ARCHIVE · Tài liệu",archive_title:"Tài liệu",archive_desc:"Xem bằng sáng chế, đăng ký thiết kế và chứng nhận của YUSUNG ACE.",archive_all:"Tất cả tài liệu",archive_filter_patent:"Bằng sáng chế",archive_filter_design:"Đăng ký TK",archive_filter_cert:"Chứng nhận",archive_stat_patent:"Bằng sáng chế",archive_stat_design:"Đăng ký TK",archive_stat_cert:"Chứng nhận",archive_stat_knowhow:"Know-how kỹ thuật",
footer_copyright:"© 2026 YUSUNG ACE. All rights reserved.",
mega_categories:"DANH MỤC",mega_full_list:"DANH SÁCH SẢN PHẨM",mega_filtered:"KẾT QUẢ LỌC"
},

zh:{
nav_home:"首页",nav_about:"公司介绍",nav_products:"产品介绍",nav_parts:"零部件",nav_gallery:"施工案例",nav_tech:"技术",nav_manual:"使用方法",nav_customer:"客户中心",nav_notice:"公告",nav_board:"论坛",nav_archive:"资料室",nav_inquiry:"施工案例 / 报价咨询",nav_contact:"联系我们",nav_core_tech:"核心技术",nav_process:"流程",nav_core_desc:"360°旋转、便捷清洁、FVD防火阀、定制生产",nav_process_desc:"从现场测量到施工及售后，4个步骤",nav_manual_desc:"产品安装与维护可视化指南",nav_notice_desc:"重要公告与活动信息",nav_board_desc:"技术资料、施工案例、产品动态",nav_archive_desc:"专利、认证证书等",nav_inquiry_desc:"按店铺规模定制设计",
hero_tag:"SINCE 2007 · YUSUNG ACE",hero_title1:"韩国排烟管道",hero_title2:"No.1",hero_sub:"引领今天的驱动力。",hero_scroll1a:"以全新的环境、全新的技术，",hero_scroll1b:"始终领先一步。",hero_scroll2a:"在信任与分享中，",hero_scroll2b:"成为备受喜爱的企业。",
feat1_title:"360°旋转",feat1_desc:"如钟摆般360°自由旋转。管道不固定，无断裂之忧，使用便捷。",feat2_title:"F.V.D 防火阀",feat2_desc:"风速调节兼防火阀，火灾时自动关闭。在200~220℃时闭合，防止火势蔓延。",feat3_title:"可拆卸清洗",feat3_desc:"无需工具，手动拆卸。卫生结构支持每日清洗。一键拆卸上部管道亦可清洁。",feat4_title:"上下伸缩调节",feat4_desc:"轴承张力调节+挡杆制动器，安全调节高度。可按需定制长度。",
fim_tag:"FEATURES IN MOTION",fim_title_a:"通过",fim_title_b:"动态",fim_title_c:"感受细节。",fim_desc:"四大核心技术如何实际运作，静静观看就能感受到。",fim_card1_tag:"01 / SWING",fim_card1_title:"360°自由旋转",fim_card1_desc:"张力螺丝机构实现上下左右360°完全自由旋转。托盘移动，管道始终保持原位。",fim_card2_tag:"02 / CLEAN",fim_card2_title:"一键拆卸清洗",fim_card2_desc:"拧一圈螺丝即可整体拆下上部管道。直接检查并清洗内部油污，支持每日清洁。",fim_card3_tag:"03 / SAFETY",fim_card3_title:"安全与维护选项",fim_card3_desc:"FVD防火阀：200~220℃时阀门关闭防止火灾。一键拆卸便于上部管道清洁。",fim_card4_tag:"04 / CUSTOM",fim_card4_title:"定制化生产",fim_card4_desc:"按您所需的长度定制生产。标准L1800规格，可截短或加长。",
www_tag:"WHERE WE WORK",www_title_a:"在韩国的",www_title_b:"烈焰前方",www_title_c:"。",www_desc:"从连锁餐厅厨房到重工业制造现场、精密实验室——友盛ACE每天守护着无数专业人士的洁净工作环境。",www_case1_tag:"USE CASE 01",www_case1_title:"炭火烤肉店",www_case1_desc:"防止每桌油脂滴落，360°旋转自由吸烟。",www_case1_btn:"查看管道系列",www_case2_tag:"USE CASE 02",www_case2_title:"大型连锁店",www_case2_desc:"全店统一规格、零部件更换标准化。F.V.D防火阀多店安全统一管理。",www_case2_btn:"查看LED照明",www_case3_tag:"USE CASE 03",www_case3_title:"工厂 / 实验室",www_case3_desc:"烟雾弥漫的车间，需要精密通风的实验室，均提供通风解决方案。",www_case3_btn:"查看Fresh Ball伞式软管",www_cta_text:"不确定哪款型号适合您的店铺？",www_cta_btn:"免费咨询",
stmt_tag:"A NEW STANDARD",stmt_title1:"全新友盛ACE，",stmt_title2:"餐饮的未来",stmt_title3:"已来。",stmt_desc:"在炭火烧烤排烟设施不断变革的时代，请体验友盛ACE倾心打造的独家技术实力。",stmt_chip1:"360° SWING",stmt_chip2:"F.V.D 防火阀",stmt_chip3:"拆卸清洗",stmt_chip4:"上下张力",stmt_chip5:"环保设计",
gp_tag:"REAL CONSTRUCTION",gp_title1:"20年积累的",gp_title2:"真实施工照片。",gp_btn:"查看全部案例",
vid_tag:"YUSUNG ACE IN ACTION",vid_title1:"友盛ACE油烟罩，",vid_title2:"看实际运行效果。",vid_desc:"观看360°旋转、上下张力、FVD防火阀的实际运行。20年经验打造的平滑精准动作。",vid_btn:"在Naver博客观看视频",
about_hero_tag:"SINCE 2007 · ABOUT US",about_hero_t1:"在信任与分享中，",about_hero_t2:"成为备受喜爱的企业。",about_hero_desc:"在引领行业创新的起点，中心始终是友盛ACE。以正确方向而非速度建立的标准，成为无法模仿的骄傲，回报客户的信任。",about_ceo_tag:"CEO MESSAGE",about_ceo_label:"总经理",about_ci_tag:"COMPANY INFO",about_ci_title:"公司信息",about_ci_ceo_title:"总经理",about_ci_biz_label:"营业执照号",about_loc_tag:"LOCATION",about_loc_title:"交通指南",about_naver_map:"Naver地图",about_kakao_map:"Kakao地图",about_promise_tag:"OUR PROMISE",about_promise_t1:"以最高技术和品质，",about_promise_t2:"通过服务实现客户满意。",about_promise_desc:"引领环保城市开发，友盛ACE自2007年起专注一条路，是韩国排烟管道No.1。",about_contact_tag:"CONTACT US",about_contact_title:"联系我们",about_contact_desc:"关于报价、安装、售后等问题，请留言，我们将尽快回复。",about_form_submit:"提交咨询",about_success_title:"咨询已提交！",about_success_desc:"负责人将尽快与您联系。",
prod_hero_tag:"PRODUCT LINEUP · 148 MODELS",prod_hero_t1:"148种产品，",prod_hero_t2:"一种匠人精神。",prod_hero_desc:"Galaxy A·B·C·D型、两侧发条、LED照明、LED飞碟、螺旋、管道、新鲜球等——通过实际照片浏览友盛ACE全产品线。",prod_cta_tag:"NEED HELP CHOOSING?",prod_cta_title:"适合您店铺的产品，直接为您推荐。",prod_cta_desc:"凭借20年经验，根据店铺规模、灶具类型和天花板高度推荐最优产品。",prod_cta_gallery:"查看施工案例",
parts_tag:"PARTS CATALOG · 50 ITEMS",parts_hero_title:"零部件介绍",parts_hero_desc:"一览友盛ACE油烟罩的所有零部件。通过实物照片查看每个零部件。",
manual_hero_title:"使用方法",manual_hero_desc:"友盛ACE产品的正确使用及维护保养方法。",
gallery_hero_tag:"CONSTRUCTION GALLERY",gallery_hero_desc:"友盛ACE施工的炭火炉油烟罩产品线。浏览Galaxy系列、亚克力灯、飞碟罩、外置发条等多种现场照片。",
process_hero_t1:"从现场测量到售后服务，",process_hero_t2:"4步一站式系统。",process_hero_desc:"20年经验的专家亲临店铺，设计、制造、施工最优解决方案。",process_tag:"OUR PROCESS",process_step1_title:"现场测量 / 咨询",process_step1_desc:"拥有20年经验的专家亲临现场，测量店铺规模、灶具类型、天花板高度，为现场环境推荐最优油烟罩系统。",process_step2_title:"定制设计与报价",process_step2_desc:"从Galaxy A~D中推荐最适合的型号，提供图纸和透明报价。综合考虑天花板高度、灶具布局和动线的定制设计。",process_step3_title:"自有工厂制造",process_step3_desc:"在友盛ACE自有工厂精密制造后直发现场。每一颗螺丝都100%国内自主生产，这是对品质的自信。",process_step4_title:"施工与售后",process_step4_desc:"专业技师施工 + F.V.D防火阀检测 + 专利零部件售后支持。施工后仍负责维护保养的一站式服务。",process_cta:"申请免费现场测量",process_cta_text:"立即获取咨询",process_cta_btn:"报价咨询",
tech_hero_tag:"TECHNOLOGY DEEP DIVE",tech_hero_t1:"8大核心技术，",tech_hero_t2:"尽在一个油烟罩内。",tech_hero_desc:"友盛ACE，20年如一日，自主设计并在现场验证的核心技术全部公开。",tech_tag:"CORE TECHNOLOGY",tech_title:"友盛ACE独有的核心技术",tech_impact:"在自有工厂自主设计与生产。",tech_3d_title:"3D油烟罩系统",tech_stat1_label:"专利技术",tech_stat1_val:"5项+",tech_stat2_label:"产品型号",tech_stat2_val:"148种",tech_stat3_label:"施工范围",tech_stat3_val:"全国",tech_stat4_label:"行业经验",tech_stat4_val:"20年",
footer_company:"友盛ACE有限公司",footer_desc:"韩国排烟管道No.1——自2007年专注炭火炉油烟罩的专业企业。以全新环境、全新技术始终领先一步。",footer_addr:"京畿道坡州市坡州邑中央产业园区1路103号",footer_addr_label:"地址",footer_tel:"电话",footer_fax:"传真",footer_ceo:"总经理",footer_ceo_name:"朴振善",footer_biz:"营业执照号",footer_rights:"All rights reserved.",footer_no1:"韩国排烟管道No.1",
lang_ko:"한국어",lang_en:"English",lang_ja:"日本語",lang_vi:"Tiếng Việt",lang_zh:"中文",
nav_about_ceo:"CEO致辞",nav_about_ceo_sub:"友盛ACE的承诺",nav_about_map:"交通指南",nav_about_map_sub:"总部及工厂位置",
mega_cat1:"Galaxy A~D型",mega_cat1_sub:"旋转发条/FVD/油脂滤网一体",mega_cat2:"两侧发条 BEST",mega_cat2_sub:"两侧发条旋转系列",mega_cat3:"LED照明 / 飞碟",mega_cat3_sub:"LED/卤素灯及亚克力灯",mega_cat4:"管道 / 螺旋",mega_cat4_sub:"不锈钢管（镀层/喷涂）· 螺旋管",mega_cat5:"新鲜球 / 软管",mega_cat5_sub:"柔性连接管",mega_view_all:"查看全部 →",
cta_tag:"SINCE 2007 · PROVEN QUALITY",cta_title1:"用过一次，",cta_title2:"就再也回不去了。",cta_desc:"没有营销，仅靠口碑成长的品质差异——请亲自体验。",cta_btn_products:"查看产品线",cta_btn_inquiry:"报价咨询",
core_title:"友盛ACE油烟罩的优势。",core_desc:"炭火烧烤排烟设施的新潮流。改善便利性，同时兼顾卫生、安全与视觉美感。",core_label_upper:"上部管道",core_label_fvd:"防火阀",core_label_lower:"下部管道",core_label_cap:"喇叭口接油盘",core_tagline:"经受摇晃却不会折断的技术",
core_f1_title:"01 桌面基准360°旋转",core_f1_desc:"管道不固定，从垂直方向如钟摆般360°旋转，完全不用担心折断。",core_f2_title:"02 便捷内部清洁",core_f2_desc:"下部管道轻松拆卸，任何人都能轻松清洁管道内部。",core_f3_title:"03 安全与维护选项",core_f4_title:"04 定制化生产",core_f4_desc:"可按所需长度定制。标准L1800规格，可截短或加长适应各种现场。",
impact_copy:"韩国的技术友盛ACE，走向世界。",stat_products:"产品线",stat_engineering:"工程技术",stat_swing:"旋转系统",stat_domestic:"国内制造",
about_ceo_name:"朴振善",about_ceo_p1:"友盛ACE是用技术实现现场价值的通风解决方案领导者。自创立以来，我们以'现场为核心的技术力'和'客户至上的价值'为基础，引领厨房通风系统的创新。",about_ceo_p2:"从设计到制造，再到实际现场施工，不漏掉一颗螺丝的精密是友盛ACE坚守的骄傲。作为国内直接生产的制造商，我们作为解决现场无数变量和难题的'伙伴'，与客户共同成长。",about_ceo_p3:"友盛ACE的所有产品追求以用户为中心的设计，最大化用户便利性。我们倾听在实际现场操作设备的人们的声音，创造更安全高效的通风环境是我们的使命。",about_ceo_p4:"未来友盛ACE承诺通过不懈的研发和严格的品质管理，提供引领韩国厨房通风文化的最佳通风解决方案。衷心感谢给予我们不变信任和支持的各位客户。",
about_addr1:"京畿道坡州市坡州邑中央产业园区1路103号",about_addr2:"(凤岩里1371-9)",about_ci_name:"友盛ACE",about_ci_ceo:"朴振善",
form_name:"姓名",form_phone:"联系方式",form_company:"公司 / 店铺名",form_type:"咨询类型",form_type_quote:"报价咨询",form_type_install:"安装咨询",form_type_as:"售后咨询",form_type_other:"其他",form_content:"咨询内容",form_phone_alt:"或致电 1588-9123",form_new_inquiry:"新咨询",
prod_stat1:"11个类别",prod_stat2:"148种实拍照片",prod_stat3:"20年技术经验",prod_no_items:"该类别暂无产品。",prod_filter_all:"全部",prod_cta_t1:"按店铺类型",prod_cta_t2:"定制推荐产品线。",prod_parts_t1:"148种产品，",prod_parts_t2:"一套标准零部件。",prod_consult_t1:"适合您店铺的型号，",prod_consult_t2:"我们帮您挑选。",prod_consult_desc:"凭借20年经验，根据店铺规模、菜单和装修风格推荐最优产品线。",prod_consult_phone:"致电 1588-9123",prod_consult_about:"查看公司信息",
manual_f1_title:"导油装置（内置接油盘）",manual_f1_desc:"使用中完全不滴油。一体成型接油盘安全收集罩内油脂，卫生管理。",manual_f1_tag:"滴油为零",manual_f2_title:"无声吸入设计",manual_f2_desc:"即使吸入口气压强也不会产生哨音。精密气流设计维持店内舒适环境。",manual_f2_tag:"强力静音吸入",manual_f3_title:"螺丝式便捷拆卸",manual_f3_desc:"连接上下部的管环为螺丝式组装，拆卸简单，任何人都能轻松清洁内部。",manual_f3_tag:"无需工具轻松拆卸",manual_f4_title:"油脂过滤网",manual_f4_desc:"过滤油脂保持电机和管道内部清洁。延长电机寿命同时预防火灾的双重效果。",manual_f4_tag:"电机寿命延长+防火",manual_f5_title:"360°自由旋转",manual_f5_desc:"管道不固定，自由摆动。如钟摆般平滑旋转，完全不会折断，桌面任意角度自由使用。",manual_f5_tag1:"管道破损为零",manual_f5_tag2:"360°旋转",manual_f5_tag3:"钟摆原理",manual_video_link:"观看友盛ACE官方视频",
gallery_hero_t1:"20年施工，",gallery_hero_t2:"遍布全国各地。",gallery_source:"图片来源: usungace.com官方作品集 · 点击查看详情",gallery_modal_desc:"说明",gallery_modal_features:"核心特征",gallery_modal_spec:"产品规格",gallery_modal_tags:"标签",
tech_hero_desc2:"友盛ACE，20年如一日，自主设计并在现场验证的核心技术全部公开。",
notice_tag:"NOTICE · 公告",notice_title:"友盛ACE动态",notice_desc:"在此查看重要公告、售后日程和活动信息。",
board_tag:"BOARD · 论坛",board_title:"论坛",board_desc:"以博客形式查看友盛ACE的技术资料、施工案例和产品动态。",board_sort_latest:"最新",board_sort_views:"最多浏览",board_sort_num:"按编号",board_col_no:"编号",board_col_cat:"分类",board_col_title:"标题",board_col_author:"作者",board_col_date:"日期",board_col_views:"浏览",
archive_tag:"ARCHIVE · 资料室",archive_title:"资料室",archive_desc:"查看友盛ACE持有的专利、设计注册和认证证书。",archive_all:"全部资料",archive_filter_patent:"专利",archive_filter_design:"设计注册",archive_filter_cert:"认证证书",archive_stat_patent:"专利",archive_stat_design:"设计注册",archive_stat_cert:"认证证书",archive_stat_knowhow:"技术经验",
footer_copyright:"© 2026 YUSUNG ACE / 友盛ACE. All rights reserved.",
mega_categories:"类别",mega_full_list:"全部产品",mega_filtered:"筛选结果"
}
};

var STORAGE_KEY="usung-lang";
var DEFAULT_LANG="ko";

function getLang(){
try{return localStorage.getItem(STORAGE_KEY)||DEFAULT_LANG}catch(e){return DEFAULT_LANG}
}

function setLang(code){
if(!T[code])return;
try{localStorage.setItem(STORAGE_KEY,code)}catch(e){}
var dict=T[code];
var els=document.querySelectorAll("[data-i18n]");
for(var i=0;i<els.length;i++){
var key=els[i].getAttribute("data-i18n");
if(dict[key]!=null)els[i].textContent=dict[key];
}
var phs=document.querySelectorAll("[data-i18n-placeholder]");
for(var j=0;j<phs.length;j++){
var pk=phs[j].getAttribute("data-i18n-placeholder");
if(dict[pk]!=null)phs[j].setAttribute("placeholder",dict[pk]);
}
document.documentElement.setAttribute("lang",code);
var evt;
try{evt=new CustomEvent("langchange",{detail:{lang:code}})}catch(e){evt=document.createEvent("CustomEvent");evt.initCustomEvent("langchange",true,true,{lang:code})}
document.dispatchEvent(evt);
}

window.I18N=T;
window.setLang=setLang;
window.getLang=getLang;

/* Re-apply translations after SPA page navigation */
function hookNavigation(){
var orig=window.navigate;
if(typeof orig==="function"){
window.navigate=function(){
var r=orig.apply(this,arguments);
setTimeout(function(){setLang(getLang())},60);
return r;
};
}
}

function init(){
setLang(getLang());
hookNavigation();
}
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",init)}else{init()}
})();
