/* usung-r8-gal.js — r8 카탈로그 이식 모듈 (시공갤러리 · 라이트박스)
 * GENERATED by build_graft.py from _proto_catalog_r8.html (JS1 746-901).
 * Do not edit by hand — edit the prototype and rebuild.
 * Loads as a classic script; shares global scope with the other r8 modules.
 */
// ===== 시공 갤러리 (r5) — style-classified install photos =====
const GALLERY={
"모던":[["gm01.jpg","125Ø스윙텐션(검정함마)스텐","연화담 설치사진",860,610],["gm02.jpg","125Ø스윙텐션(검정함마)스파이얼","450Ø갓",860,762],["gm03.jpg","125Ø스윙텐션(은)스텐","450Ø우주선",860,791],["gm04.jpg","125Ø스윙텐션(은)스텐","직화명가본점1",860,645],["gm05.jpg","125Ø스윙텐션(은)스텐","직화명가본점3",860,645],["gm06.jpg","125Ø스윙텐션(흑도금)스텐(90-110)우본관","",860,685],["gm07.jpg","125Ø스윙텐션(흑도금)스텐","규돈향",860,880],["gm08.jpg","125Ø스윙텐션(흑도금)스텐","규돈향1",827,1100],["gm09.jpg","125Ø스윙텐션(흑도금)스텐","그릴마스터킴",860,677],["gm10.jpg","125Ø스윙텐션(흰색도장)스텐","",825,1100],["gm11.jpg","125Ø스윙텐션(흰색함마)스텐","450Ø우주선",825,1100],["gm12.jpg","150Ø스윙양옆태엽(태엽검정-신형)(검정함마)스파이얼","위드휴먼1",860,484],["gm13.jpg","150Ø스윙양옆태엽(태엽검정-신형)(검정함마)스파이얼","위드휴먼2",860,484],["gm14.jpg","150Ø스윙텐션(흑도금)304스텐","홍고박",860,922],["gm15.jpg","FVD스윙텐션(검정함마)스텐","(90-110)닥트몬스터",860,645],["gm16.jpg","FVD스윙텐션(헤어라인)스텐","진원소우대전관평점",860,999],["gm17.jpg","사각측향FVD스윙텐션(검정함마)스텐","(90-110)닥트몬스터1",825,1100],["gm18.jpg","측향스윙텐션(은)스텐","450갓등",860,1063],["gm19.jpg","측향스윙텐션(흰색함마)스텐","450갓등",860,917]],
"클래식":[["gc01.jpg","(확인)125Ø스윙텐션(검정함마)스파이얼","350Ø갓",620,1100],["gc02.jpg","(확인)125Ø스윙텐션(노랑함마)스파이얼","520Ø갓등",860,576],["gc03.jpg","125Ø(검정도장)자바라","도포식당",860,584],["gc04.jpg","125Ø(검정도장)자바라","운정삼겹매장사진",860,1022],["gc05.jpg","125Ø스윙양옆태엽(태엽흰색-신형)(은)스텐","온양닥트",860,645],["gc06.jpg","125Ø스윙텐션(검정함마)스파이얼","350Ø갓(얕은갓)",860,860],["gc07.jpg","125Ø스윙텐션(검정함마)스파이얼","450Ø갓1",860,860],["gc08.jpg","125Ø스윙텐션(동)스텐","",860,448],["gc09.jpg","125Ø스윙텐션(동)스텐","육일관구의직영점",779,1100],["gc10.jpg","125Ø스윙텐션(동함마)스파이얼","450Ø갓등",860,861],["gc11.jpg","125Ø스윙텐션(동함마)스파이얼","도쿄화로인천연수점2",860,863],["gc12.jpg","125Ø스윙텐션(동함마)스파이얼","도쿄화로인천연수점3",860,1072],["gc13.jpg","125Ø스윙텐션(은)스텐","",860,645],["gc14.jpg","125Ø스윙텐션(흰색도장)스텐","",825,1100],["gc15.jpg","125Ø스윙텐션(흰색함마)스텐","450Ø우주선",825,1100],["gc16.jpg","150Ø스윙양옆태엽(태엽검정-신형)(헤어라인)304스텐","",860,645],["gc17.jpg","150Ø스윙텐션(동함마)스텐","5단유지망",860,645],["gc18.jpg","150Ø스윙텐션(동함마)스파이얼","",619,1100],["gc19.jpg","FVD스윙텐션(검정함마)스텐","(90-110)닥트몬스터",860,645],["gc20.jpg","FVD스윙텐션(검정함마)스파이얼(90-110)","",860,645],["gc21.jpg","FVD스윙텐션(신주)스텐(나팔 구형)","",860,627],["gc22.jpg","FVD스윙텐션(헤어라인)스텐","진원소우대전관평점",860,999],["gc23.jpg","무도장스파이얼","레트로감성",860,1031],["gc24.jpg","사각측향FVD스윙텐션(검정함마)스텐","(90-110)닥트몬스터1",825,1100],["gc25.jpg","은자바라","",860,645],["gc26.jpg","측향스윙텐션(동함마)스파이얼(90-110)","",860,564]],
"프리미엄":[["gp01.jpg","125Ø스윙텐션(동)스텐","450Ø갓등",860,1038],["gp02.jpg","125Ø스윙텐션(동)스텐","450Ø갓등",860,484],["gp03.jpg","150Ø스윙양옆태엽(태엽검정-신형)(검정함마)스파이얼","위드휴먼1",860,484],["gp04.jpg","150Ø스윙양옆태엽(태엽검정-신형)(검정함마)스파이얼","위드휴먼2",860,484],["gp05.jpg","150Ø스윙양옆태엽(태엽검정-신형)(헤어라인)304스텐","",860,645],["gp06.jpg","150Ø스윙양옆태엽(태엽흰색-구형)(헤어라인)304스텐","",860,943],["gp07.jpg","150Ø스윙텐션(동함마)스텐","5단유지망",860,645],["gp08.jpg","150Ø스윙텐션(동함마)스파이얼","",619,1100],["gp09.jpg","150Ø스윙텐션(동함마)스파이얼","520Ø갓",823,1100],["gp10.jpg","150Ø스윙텐션(헤어라인)304스텐","",766,1100],["gp11.jpg","150Ø스윙텐션(흑도금)304스텐","홍고박",860,922],["gp12.jpg","304스텐350파이갓","",860,629],["gp13.jpg","측향스윙텐션(은)스텐","450갓등",860,1063],["gp14.jpg","측향스윙텐션(흰색함마)스텐","450갓등",860,917]],
"레트로":[["gr01.jpg","(확인)125Ø스윙텐션(노랑함마)스파이얼","520Ø갓등",860,576],["gr02.jpg","(확인)125Ø스윙텐션","빨간우주선",860,635],["gr03.jpg","125Ø(검정도장)자바라","도포식당",860,584],["gr04.jpg","125Ø(검정도장)자바라","운정삼겹매장사진",860,1022],["gr05.jpg","125Ø스윙텐션(검정함마)스텐","아크릴원통등(빨강, 노랑)",860,655],["gr06.jpg","125Ø스윙텐션(검정함마)스텐","아크릴원통등(빨강-구형)",860,644],["gr07.jpg","125Ø스윙텐션(동함마)스텐","아크릴원통등(구형)",860,645],["gr08.jpg","무도장스파이얼","레트로감성",860,1031],["gr09.jpg","은자바라","",860,645],["gr10.jpg","코브라(실버함마)","동래정신풍역점",806,1100]]
};
const GAL_ORDER=['클래식','모던','프리미엄','레트로'], GAL_CATS=['전체',...GAL_ORDER];
let galCat='전체', galList=[], lbIdx=0;
function clnSpec(s){return (s||'').replace(/^\(확인\)/,'').trim();}
function galItems(cat){
  const mk=(a,c)=>({src:a[0],spec:a[1],site:a[2],w:a[3],h:a[4],cat:c});
  if(cat!=='전체') return GALLERY[cat].map(a=>mk(a,cat));
  const seen=new Set(), out=[];  // dedup shared installs across styles
  GAL_ORDER.forEach(c=>GALLERY[c].forEach(a=>{const k=a[1]+'|'+a[2];if(seen.has(k))return;seen.add(k);out.push(mk(a,c));}));
  return out;
}
function galCount(cat){return cat==='전체'?galItems('전체').length:GALLERY[cat].length;}
function goGallery(){showView('v-gallery');setNav('nav-gal');window.scrollTo(0,0);renderGallery('전체');}
// r31/S18 — 칩 줄 맨 앞에 붙는 안내 패널.
// 덱 260812_홈페이지_수정_r2 S18:「원하던 스타일로 안 들어감 … 시공갤러리에 이런 표현이
// 강조가 됐으면 좋겠어서 이렇게 만들어주세요 · 빨간 네모박스와같이!」
// 이 문구(.gal-find)는 원래 마크업에 있었는데 r10 이 「헤더가 두 번 나오고 그리드를 접힘
// 아래로 민다」는 이유로 display:none 했다. 승연이 원한 건 삭제가 아니라 **칩 줄 왼쪽
// 인라인 배치**다. .gal-find 는 계속 숨긴 채 같은 문구를 여기서 다시 넣는다.
// ★ #gal-tabs 는 renderGalTabs 가 innerHTML 로 통째로 다시 그린다. DOM 삽입이 아니라
//   생성 문자열에 넣어야 필터 클릭 후에도 살아남는다(r9 전화 CTA 도 같은 이유로 관찰자 재주입).
// ★ .gal-tab 이 아니라 div 라서 r9-excel 의 '#gal-tabs .gal-tab.on' 조회에 안 걸린다.
// ★ <br> 로 두 줄 나눈 건 r16 사전이 「원하는 디자인을」·「빠르게 찾아보세요」를 각각
//   한 행으로 갖고 있어서다(usung-r16-i18n-a.js:57-58). 한 덩어리로 합치면 번역이 끊긴다.
// ★ r32 / r3 덱 s5 — 「원하는 디자인을 빠르게 찾아보세요**만 키우고, 스타일별 삭제**」.
//   r2 덱 S18 이 복원하라고 한 원본 패널에는 「스타일별 ⌄」 드롭다운이 함께 있었고 나도
//   그대로 되살렸는데(.gf-k), r3 에서 그건 빼라고 정정이 왔다. 라벨을 지우고 문구를 키운다.
//   확대는 usung-r31.css 의 `.gf-lead b` 에서 한다(여기는 마크업만).
const GAL_FIND='<div class="gf-lead"><b>원하는 디자인을<br>빠르게 찾아보세요</b></div>';
function renderGalTabs(){
  // 260729: 제품소개의 스타일 칩(아이콘+개수)을 시공갤러리 탭으로 이관
  document.getElementById('gal-tabs').innerHTML=GAL_FIND+GAL_CATS.map(c=>
    `<button class="gal-tab${c===galCat?' on':''}" onclick='filterGallery("${c}")'>`
    +(c==='전체'?'':`<span class="gt-ic">${iconFor(c)}</span>`)
    +`${c}<span>${galCount(c)}</span></button>`).join('');
}
// r7.1: block-snapping FLIP filter — surviving tiles glide to their new grid
// slots, entering tiles pop in, exiting tiles shrink away (no full fade-out).
const GAL_DIR='proto_assets/gallery/';
const GAL_ZOOM='<span class="gt-zoom" aria-hidden="true"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"></circle><line x1="21" y1="21" x2="16.7" y2="16.7"></line><line x1="11" y1="8" x2="11" y2="14"></line><line x1="8" y1="11" x2="14" y2="11"></line></svg></span>';
function galInner(it,i){
  // caption matches live-site reference: "NNN · 시공갤러리" kicker + "시공 현장 NN" title
  const n2=String(i+1).padStart(2,'0'), n3=String(i+1).padStart(3,'0');
  return `<img loading="lazy" src="${GAL_DIR}${it.src}" alt="시공 현장 ${n2}">${GAL_ZOOM}<figcaption><span class="gt-cat">${n3} · 시공갤러리</span><span class="gt-site">시공 현장 ${n2}</span></figcaption>`;
}
function galMakeTile(it,i){
  const f=document.createElement('figure');
  f.className='gtile g-init'; f.dataset.key=it.src;
  f.setAttribute('onclick','openLbox('+i+')');
  f.innerHTML=galInner(it,i);
  return f;
}
function galSyncTile(el,it,i){ // reuse a surviving tile: refresh index + caption number (both kicker + title carry the number)
  el.setAttribute('onclick','openLbox('+i+')');
  const c=el.querySelector('.gt-cat'); if(c) c.textContent=String(i+1).padStart(3,'0')+' · 시공갤러리';
  const s=el.querySelector('.gt-site'); if(s) s.textContent='시공 현장 '+String(i+1).padStart(2,'0');
}
function renderGallery(cat){
  galCat=cat; renderGalTabs(); galList=galItems(cat);
  const grid=document.getElementById('gal-grid'); grid.innerHTML='';
  const tiles=galList.map((it,i)=>{const t=galMakeTile(it,i);grid.appendChild(t);return t;});
  void grid.offsetWidth; // commit start state
  tiles.forEach((el,i)=>setTimeout(function(){el.classList.remove('g-init');el.classList.add('g-in');}, 20+i*20));
}
function filterGallery(cat){
  if(cat===galCat) return;
  const grid=document.getElementById('gal-grid');
  const oldTiles=[].slice.call(grid.children);
  // reduced-motion: swap instantly with no choreography
  if(window.matchMedia && window.matchMedia('(prefers-reduced-motion:reduce)').matches){
    renderGallery(cat); return;
  }
  galCat=cat; renderGalTabs(); galList=galItems(cat);
  const gr0=grid.getBoundingClientRect();
  const cx=gr0.width/2, cy=gr0.height/2; // grid-local center point
  // EXIT — measure every current tile in-flow, freeze all to absolute, then converge
  // them toward the center while shrinking + fading (뭉침 / gather-in).
  const meas=oldTiles.map(function(el){const r=el.getBoundingClientRect();
    return {el:el,x:r.left-gr0.left,y:r.top-gr0.top,w:r.width,h:r.height};});
  meas.forEach(function(m){const el=m.el;
    el.classList.remove('g-init','g-in','g-out');
    el.style.position='absolute';el.style.margin='0';el.style.zIndex='1';
    el.style.left=m.x+'px';el.style.top=m.y+'px';el.style.width=m.w+'px';el.style.height=m.h+'px';
    el.style.transition='none';el.style.transform='none';el.style.opacity='1';});
  void grid.offsetWidth; // commit frozen absolute state
  meas.forEach(function(m){const el=m.el;
    const dx=cx-(m.x+m.w/2), dy=cy-(m.y+m.h/2);
    el.style.transition='transform .5s cubic-bezier(.55,0,.85,.25),opacity .42s ease';
    el.style.transform='translate('+dx+'px,'+dy+'px) scale(.3)';
    el.style.opacity='0';});
  setTimeout(function(){meas.forEach(function(m){if(m.el.parentNode)m.el.parentNode.removeChild(m.el);});},560);
  // ENTER — r8Build the new set, park each tile clustered at the center (invisible), then
  // bloom them outward to their slots (펼침 / spread-out), radially staggered so inner
  // tiles open first. Old tiles are absolute, so new tiles measure correct slots.
  const enterDelay = oldTiles.length ? 340 : 0;
  const tiles=galList.map(function(it,i){const t=galMakeTile(it,i);grid.appendChild(t);return t;});
  const info=tiles.map(function(el){const r=el.getBoundingClientRect();
    const tcx=(r.left-gr0.left)+r.width/2, tcy=(r.top-gr0.top)+r.height/2;
    return {el:el,dx:cx-tcx,dy:cy-tcy,dist:Math.hypot(cx-tcx,cy-tcy)};});
  info.forEach(function(o){o.el.classList.remove('g-init','g-in');
    o.el.style.transition='none';
    o.el.style.transform='translate('+o.dx+'px,'+o.dy+'px) scale(.3)';
    o.el.style.opacity='0';});
  void grid.offsetWidth; // commit clustered start state
  const maxDist=Math.max.apply(null,info.map(function(o){return o.dist;}))||1;
  info.forEach(function(o){const step=Math.round(o.dist/maxDist*300); // radial stagger 0..300ms
    setTimeout(function(){
      o.el.style.transition='transform .62s cubic-bezier(.2,.72,.28,1),opacity .5s ease';
      o.el.style.transform='none';o.el.style.opacity='1';
    },enterDelay+step);
    setTimeout(function(){ // clear inline overrides so CSS hover transitions resume
      o.el.style.transition='';o.el.style.transform='';o.el.style.opacity='';
      o.el.classList.add('g-in');
    },enterDelay+step+680);
  });
}
function openLbox(i){lbIdx=i;renderLbox();document.getElementById('lbox').classList.add('on');document.body.style.overflow='hidden';}
function closeLbox(){document.getElementById('lbox').classList.remove('on');document.body.style.overflow='';}
function stepLbox(d){const n=galList.length;lbIdx=(lbIdx+d+n)%n;renderLbox();}
// r6: parse a gallery spec string into structured product facts (기획의도 3)
function parseSpec(s){
  s=clnSpec(s);
  const size=(s.match(/(\d+)\s*Ø/)||s.match(/(\d+)\s*파이/)||[])[1]||'';
  let struct;
  if(/코브라/.test(s))struct='360° 스윙 코브라 후드';
  else if(/양옆태엽|양측태엽/.test(s))struct='양옆태엽 스윙 후드';
  else if(/측향/.test(s))struct='측향 배기 후드';
  else if(/자바라/.test(s))struct='자바라 신축형 후드';
  else if(/스윙텐션|텐션/.test(s))struct='와이어리스 스윙텐션 후드';
  else struct='유성에이스 후드';
  const parens=[...s.matchAll(/\(([^)]+)\)/g)].map(m=>m[1]).filter(p=>!/태엽/.test(p)&&!/\d+-\d+/.test(p));
  const color=parens.length?parens[parens.length-1]:'';
  let body='';
  if(/304스텐/.test(s))body='304 스테인리스';
  else if(/스파이얼/.test(s))body='스파이얼 바디';
  else if(/우주선/.test(s))body='우주선 바디';
  else if(/스텐/.test(s))body='스테인리스 바디';
  return {size,struct,color,body,fvd:/FVD/.test(s)};
}
function renderLbox(){
  const it=galList[lbIdx];
  document.getElementById('lb-img').src='proto_assets/gallery/'+it.src;
  const p=parseSpec(it.spec);
  const chips=[it.cat,p.color,p.body,p.fvd?'FVD 방화':''].filter(Boolean).map(c=>`<span>${c}</span>`).join('');
  const store=it.site?`📍 ${it.site}`:'';
  document.getElementById('lb-cap').innerHTML=
    `<div class="lb-brand">이 매장에 시공된 제품</div>
     <div class="lb-prod">${p.size?p.size+'Ø ':''}${p.struct}</div>
     ${store?`<div class="lb-store">${store}</div>`:''}
     <div class="lb-chips">${chips}</div>
     <div class="lb-cta">
       <a class="lb-btn primary tel-link" href="${telHref()}">${TEL_LABEL}로 문의하기 <b>&rarr;</b></a>
     </div>`;
}

document.addEventListener('keydown',e=>{
  const lb=document.getElementById('lbox');
  if(lb&&lb.classList.contains('on')){
    if(e.key==='Escape')closeLbox();else if(e.key==='ArrowLeft')stepLbox(-1);else if(e.key==='ArrowRight')stepLbox(1);return;
  }
  if(e.key==='Escape'){if(document.getElementById('fmask').classList.contains('on'))closeFirst();else if(document.getElementById('pmask').classList.contains('on'))closePart();else r8CloseModal();return;}
  if(document.getElementById('pmask').classList.contains('on'))return;
  if(e.key==='ArrowLeft')stepFinish(-1);if(e.key==='ArrowRight')stepFinish(1);
});
