/* usung-r8-view.js — r8 뷰 마크업 (GENERATED by build_graft.py)
 * 라이브 .page 컨테이너 안에 .r8x 스코프로 마운트된다.
 */

window.R8_VIEW = {
  'v-main': `<section id="v-main" class="view on">
  
  <div class="hero">
    <div class="hero-bg"></div>
    <div class="hero-veil"></div>
    <div class="hero-sweep"></div>
    <div class="wrap">
    <div class="hero-copy">
      <div class="hero-kicker">PRODUCT COLLECTION</div>
      <div class="hero-h1"><span class="num" id="hnum">0</span><span>MODELS</span></div>
      <div class="hero-sub">20년 기술력으로 완성한<br>국내 최대 후드 라인업</div>
      <div class="hero-feats"><span>20년 기술력</span><span>국내 생산</span><span>다양한 디자인</span><span>맞춤 제작</span></div>
      <div class="hero-cta-row">
        <button class="hero-btn" onclick="scrollFilter()">제품 전체 보기 →</button>
      </div>
    </div>
    <div class="hero-visual">
      <div class="hero-imgs" id="hero-imgs"></div>
    </div>
    </div>
  </div>

  
  <div class="filterrow" id="filterrow"><div class="wrap">
    <div class="cn-head">
      <span class="cn-k">PRODUCT CATEGORY</span>
      <h2>제품 대분류에서<br>바로 찾아보세요</h2>
      <p class="cn-d">5개 대분류 · <b id="cn-total">0</b>개 모델. 원하는 시리즈를 눌러 전체 라인업을 확인하세요.</p>
    </div>
    <div class="cn-grid" id="cn-grid"></div>
  </div></div>

  
  <div id="bands"></div>

  
  <section class="parts-sec reveal" aria-label="부품 · 구성품">
    <div class="parts-sec-head">
      <div class="ps-l">
        <span class="ps-en">PARTS &amp; COMPONENTS</span>
        <h3 class="ps-h">후드를 완성하는 부품 · 구성품 <b>48종</b></h3>
        <p class="ps-d">태엽감속기 · 모터 · 댐퍼 · 유지망 · 갓 · 후레쉬볼까지 — 후드에 들어가는 정품 부품 48종입니다. 대표 4종을 먼저 확인해 보세요.</p>
      </div>
      <button class="ps-all" onclick="goParts()">부품 전체 48종 보기 <b>→</b></button>
    </div>
    <div class="pp-grid pp-4" id="parts-cat-grid"></div>
  </section>

  
  <div class="cta reveal">
    <div class="cta-l">
      <h3>원하는 제품을 찾지 못하셨나요?</h3>
      <p>고객님의 공간에 맞춤형 후드를 제안해 드립니다. 대표전화로 문의해 주세요.</p>
      <a class="btn" id="cta-tel" href="#">대표전화 상담하기 →</a>
    </div>
    <div class="cta-r" id="cta-r"></div>
  </div>
</section>`,
  'v-cat': `<section id="v-cat" class="view">
  
  <div class="cv-top slim"><div class="wrap">
    <button class="back-btn" onclick="goMain()">← 전체 제품</button>
  </div></div>
  <div class="wrap"><div class="cv-body">
    <aside class="cv-tree"><div class="tt">카테고리</div><div id="cv-tree"></div></aside>
    <div class="cv-main" id="cv-main"></div>
  </div></div>
</section>`,
  'v-parts': `<section id="v-parts" class="view">
  <div class="cv-top slim"><div class="wrap">
    <button class="back-btn" onclick="goMain()">← 전체 제품</button>
  </div></div>
  <div class="wrap" style="padding:30px 0 70px"><div id="parts-body"></div></div>
</section>`,
  'v-tech': `<section id="v-tech" class="view">
  
  <div class="th-hero">
    <div class="th-bg" aria-hidden="true"></div>
    <div class="th-veil" aria-hidden="true"></div>
    <div class="hero-sweep" aria-hidden="true"></div>
    <div class="wrap">
      <div class="th-kick reveal">기술이 다르면, 결과가 다릅니다</div>
      <h1 class="th-h1 reveal">유성에이스가 만든<br><span class="hl">최초의 기술</span></h1>
      <p class="th-sub reveal">20년의 기술력과 끊임없는 혁신으로<br>대한민국 후드 시장의 기준을 만들어갑니다.</p>
    </div>
  </div>

  
  <div class="th-firsts"><div class="wrap">
    <div class="th-first" id="th-first"></div>
  </div></div>

  
  <div class="bs">
    <div class="bs-open"><div class="wrap">
      <div class="bs-tx">
        <div class="bs-k reveal"><i></i>BRAND STORY</div>
        <div class="bs-since reveal"><em>SINCE</em><b>1979</b></div>
        <h2 class="bs-h reveal">당연했던 불편을,<br><span class="hl">당연하지 않게.</span></h2>
        <div class="bs-lines reveal">
          <span>유성에이스의 시작은 제조업이 아니었습니다.</span>
          <span class="q">1979년부터 수많은 현장에서 덕트를 설치했고,<br>그곳에서 사람들의 불편을 보았습니다.</span>
          <span>설치가 어렵고, 사용이 불편하고, 관리가 번거로운 현실.</span>
        </div>
        <div class="bs-stmt reveal">그 불편을 해결하기 위해<br>직접 만들기 시작했습니다.</div>
      </div>
      <div class="bs-ph reveal">
        <figure class="f1"><img loading="lazy" src="bh/p1-1.jpg" alt="유성에이스 덕트 설치 현장"></figure>
        <figure class="f2"><img loading="lazy" src="bh/p1-2.jpg" alt="유성에이스 제작 현장"></figure>
      </div>
    </div></div>
    <div class="bs-chs" id="bs-chs"></div>
    <div class="bs-bridge"><div class="wrap">
      <p class="reveal">현장에서 시작된 질문들은 <b>독자적인 기술</b>이 되었고,<br>그 기술은 여러 <b>특허</b>로 이어졌습니다.</p>
    </div></div>
  </div>

  
  <div class="th-cert">
    <div class="wrap">
      <div class="th-cap-k reveal">CERTIFIED TECHNOLOGY</div>
      <h2 class="th-cap-h reveal">특허와 인증으로 증명된 기술력</h2>
      <p class="th-cap-s reveal">유성에이스의 기술은 특허와 인증으로 보호받고 있습니다.</p>
      <div class="cert-row reveal" id="cert-row"></div>
    </div>
    
    <div class="th-badges reveal" id="th-badges"></div>
  </div>

  
  <div class="th-stats">
    <div class="wrap" id="th-stats"></div>
  </div>

  
  <div class="th-sites">
    <div class="wrap">
      <div class="th-cap-k reveal">GLOBAL INSTALLATION</div>
      <h2 class="th-cap-h reveal">설치 현장</h2>
      <div class="site-grid reveal" id="site-grid"></div>
    </div>
  </div>
  
  <div class="bs-close"><div class="wrap">
    <div class="bs-cl-lines reveal">
      <span>사람들이 더 편하게 설치할 수 있도록.</span>
      <span>더 안전하게 사용할 수 있도록.</span>
      <span>더 오래 사용할 수 있도록.</span>
    </div>
    <p class="bs-cl-body reveal">사람을 위한 고민을 멈추지 않았고, 그 고민이 쌓여 오늘의 유성에이스를 만들었습니다.<br>앞으로도 변하지 않을 것은 하나입니다. <b>사용하는 사람의 입장에서 먼저 생각하는 것.</b><br>작은 불편을 해결하는 일이, 결국 누군가의 더 큰 성공으로 이어진다고 믿습니다.</p>
    <div class="bs-sign reveal">Yes, for Your Success with ACE</div>
    <div class="bs-sign-s reveal">USUNG ACE</div>
  </div></div>
</section>`,
  'v-gallery': `<section id="v-gallery" class="view">
  <div class="gal-hero"><div class="wrap">
    <div class="gal-k">CONSTRUCTION GALLERY</div>
    <h1 class="gal-h">시공 갤러리</h1>
    <p class="gal-s">유성에이스가 시공한 직화기 후드 라인업. 갤럭시 시리즈, 아크릴등, 우주선 후드, 외부태엽 등 다양한 현장 사진을 스타일별로 만나보세요.</p>
  </div></div>
  
  <div class="gal-find"><div class="wrap">
    <h2>원하는 디자인을<br>빠르게 찾아보세요</h2>
    <p>스타일을 선택하면 해당 분위기의 시공 현장만 모아 보여드립니다.</p>
  </div></div>
  <div class="wrap">
    <div class="gal-tabs" id="gal-tabs"></div>
    <div class="gal-grid" id="gal-grid"></div>
  </div>
</section>


<div class="lbox" id="lbox" onclick="if(event.target===this)closeLbox()">
  <button class="lb-x" onclick="closeLbox()">×</button>
  <button class="lb-nav l" onclick="stepLbox(-1)">‹</button>
  <figure class="lb-fig"><img id="lb-img" src="" alt="">
    <figcaption class="lb-info" id="lb-cap"></figcaption></figure>
  <button class="lb-nav r" onclick="stepLbox(1)">›</button>
</div>


<div class="mask" id="mask" onclick="if(event.target===this)r8CloseModal()">
  <div class="modal">
    <div class="m-top">
      <div class="m-crumb" id="m-crumb"></div>
      <div class="m-idx" id="m-idx"></div>
      <button class="m-x" onclick="r8CloseModal()">×</button>
    </div>
    <div class="m-body">
      <div class="m-img">
        <button class="arrow l" onclick="stepFinish(-1)" id="m-prev">‹</button>
        <img id="m-img" crossorigin="anonymous" src="" alt="">
        <button class="arrow r" onclick="stepFinish(1)" id="m-next">›</button>
      </div>
      <div class="m-info">
        <div class="m-cat" id="m-cat"></div>
        <div class="m-name" id="m-name"></div>
        <div class="m-finnow" id="m-finnow"></div>
        <div class="m-attrs" id="m-attrs"></div>
        <div class="m-spec-t">기본 규격</div>
        <table class="spec-tbl" id="m-spec"></table>
        <a class="btn-inq" data-tel href="#">대표전화 문의하기</a>
      </div>
    </div>
    <div class="m-opts" id="m-opts"></div>
    <div class="m-parts" id="m-parts"></div>
  </div>
</div>


<div class="pmask" id="pmask" onclick="if(event.target===this)closePart()">
  <div class="pmodal">
    <button class="pm-x" onclick="closePart()">×</button>
    <div class="pm-img"><img id="pm-img" src="" alt=""></div>
    <div class="pm-info">
      <div class="pm-cat" id="pm-cat"></div>
      <div class="pm-name" id="pm-name"></div>
      <div class="pm-sp" id="pm-sp"></div>
      <p class="pm-desc" id="pm-desc"></p>
      <div class="pm-use-t">사용 제품군</div>
      <div class="pm-use" id="pm-use"></div>
      <a class="pm-inq" data-tel href="#">대표전화 문의하기</a>
    </div>
  </div>
</div>


<div class="fmask" id="fmask" onclick="if(event.target===this)closeFirst()">
  <div class="fmodal">
    <button class="fm-x" onclick="closeFirst()">×</button>
    <div class="fm-body">
      <span class="fm-badge">국내 최초</span>
      <div class="fm-title" id="fm-title"></div>
      <div class="fm-sub" id="fm-sub"></div>
      <p class="fm-desc" id="fm-desc"></p>
      <ul class="fm-points" id="fm-points"></ul>
      <div class="fm-note" id="fm-note"></div>
      <button class="fm-cta" id="fm-cta">해당 제품 보기 <b>→</b></button>
    </div>
  </div>
</div>`,
};
