/* usung-r8-tech.js — r8 카탈로그 이식 모듈 (기술력 (브랜드 히스토리 · 인증 · 시공현장))
 * GENERATED by build_graft.py from _proto_catalog_r8.html (JS1 519-745).
 * Do not edit by hand — edit the prototype and rebuild.
 * Loads as a classic script; shares global scope with the other r8 modules.
 */
// ===== TECH PAGE (기술력 · S20) =====
// hero: photographic dark background (cat_led.jpg) + dark veil, like the product hero
const FIRSTS=[
 {src:'proto_assets/tf_black.png', t:'와이어없이 상하작동 텐션',cat:'파이프',key:'파이프|텐션|스텐도금',
   d:'와이어 없이 구조만으로<br>부드러운 상하 작동 구현',
   sub:'와이어리스 텐션 승강 구조',
   body:'기존 후드는 와이어와 도르래로 높이를 조절해, 시간이 지나면 와이어가 늘어나거나 끊어지고 작동이 뻑뻑해지는 문제가 있었습니다. 유성에이스는 와이어를 완전히 배제하고, 자체 개발한 텐션 구조만으로 후드를 부드럽게 올리고 내릴 수 있는 방식을 국내 최초로 구현했습니다.',
   points:[
     {h:'와이어 완전 제거',p:'끊김·엉킴·늘어짐 걱정이 없어 반영구적으로 사용할 수 있습니다.'},
     {h:'부드러운 승강감',p:'어느 높이에서도 균일한 힘으로 정지하고, 원하는 위치에 정확히 고정됩니다.'},
     {h:'유지보수 최소화',p:'소모성 부품이 없어 교체 주기가 길고 관리 비용이 절감됩니다.'}
   ],
   note:'파이프 시리즈 · 스텐도금 라인에 적용'},
 {src:'proto_assets/tf_silver.png',t:'외장형 양옆태엽',cat:'갤럭시',key:'갤럭시|갤럭시A|양옆태엽',
   d:'양측 대엽 스프링 작동으로<br>더욱 안정적인 작동',
   sub:'양측 대엽 스프링 밸런스 구조',
   body:'한쪽에만 스프링을 두면 장시간 사용 시 힘이 한쪽으로 쏠려 후드가 기울거나 처지기 쉽습니다. 갤럭시A는 양측에 대엽(大葉) 스프링을 배치해 좌우 힘을 균등하게 분산하는 구조를 적용, 어느 위치에서도 흔들림 없이 안정적으로 멈추고 작동합니다.',
   points:[
     {h:'좌우 밸런스',p:'양측 스프링이 힘을 나눠 받아 처짐과 기울어짐을 방지합니다.'},
     {h:'정밀한 정지감',p:'원하는 높이에서 정확하게 고정되어 사용이 편리합니다.'},
     {h:'내구 수명 향상',p:'편하중이 줄어 스프링 피로도가 낮아 오래 사용할 수 있습니다.'}
   ],
   note:'갤럭시 시리즈 · 갤럭시A(양옆태엽) 라인에 적용'},
 {src:'proto_assets/tf_copper.png',t:'360도 스윙',cat:'코브라후드',key:'코브라후드||90Ø롱망코브라220',
   d:'360° 자유 회전으로<br>후드 각도 조절 가능',
   sub:'360° 자유 회전 코브라 암',
   body:'조리 위치와 연기 방향은 매장마다 다릅니다. 코브라후드는 후드 암이 360° 자유롭게 회전하도록 설계되어, 배기가 필요한 방향으로 후드를 자유롭게 돌려 사용할 수 있습니다. 좁은 매장이나 다구(多口) 조리대에서도 배기 효율을 극대화합니다.',
   points:[
     {h:'360° 회전',p:'조리 위치에 맞춰 배기구를 자유롭게 조준할 수 있습니다.'},
     {h:'공간 효율',p:'하향식 구조로 천장·상부 공간을 차지하지 않습니다.'},
     {h:'다양한 규격',p:'90Ø 롱망 코브라 등 매장 규모에 맞춰 선택할 수 있습니다.'}
   ],
   note:'하향식 후드 · 코브라 라인에 적용'},
 /* ★ 덱 S19 는 이 카드의 **명칭만** 「FVD불꽃차단 시스템 → 필터(기름받이속, 기름받이망)」로 바꾸라고 했다.
    카드 앞면(t·d)까지만 새 이름에 맞췄다. d 는 지어낸 문장이 아니라 i18n.js 의 유지망필터 설명을 그대로 옮긴 것이다.
    아래 sub·body·points·note·key 는 여전히 FVD 내용이다 — 덱이 대체 문안을 주지 않아 건드리지 않았다. 문안 받으면 교체할 것. */
 {src:'proto_assets/tf_cobra.png', t:'필터(기름받이속, 기름받이망)',cat:'갤럭시',key:'갤럭시|갤럭시B|304스텐-양옆태엽(FVD)',
   d:'기름을 여과해 모터와<br>덕트 내부를 청결하게 유지',
   sub:'FVD 불꽃 역화 차단 댐퍼',
   body:'숯·불판 조리 중 튀어 오른 불꽃이 배기 덕트로 빨려 들어가면 화재로 이어질 수 있습니다. 갤럭시B의 FVD(Flame Vapor Damper) 구조는 배기 경로에서 불꽃의 역화를 물리적으로 차단해, 조리 중 화재 위험을 크게 낮추고 안전한 배기 환경을 유지합니다.',
   points:[
     {h:'불꽃 역화 차단',p:'덕트로 유입되는 불꽃을 구조적으로 차단해 화재 위험을 낮춥니다.'},
     {h:'304 스테인리스',p:'내열·내식성이 우수한 고급 소재를 적용했습니다.'},
     {h:'양옆태엽 결합',p:'안정적인 승강 구조와 안전 기능을 동시에 갖췄습니다.'}
   ],
   note:'갤럭시 시리즈 · 갤럭시B(304스텐 FVD) 라인에 적용'}
];
const CERTS=[
 {n:1,c:'특허 제10-2743423호'},{n:2,c:'특허 제10-2755661호'},{n:3,c:'특허 제10-2889700호'},
 {n:4,c:'특허 제10-2916160호'},{n:5,c:'특허 출원 진행'},{n:6,c:'디자인 등록증'}
];
// faithful colored recreations of the actual certification marks (PPT image21)
const CBADGES=[
 {i:'<svg viewBox="0 0 64 64"><rect x="6" y="12" width="52" height="40" rx="6" fill="#fff" stroke="#12357e" stroke-width="2.4"/><text x="32" y="43" text-anchor="middle" font-family="Arial Black,Arial,sans-serif" font-weight="900" font-size="30" letter-spacing="-2" fill="#12357e">KC</text></svg>',t:'KC 인증',s:'전기용품 안전인증'},
 {i:'<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="29" fill="#fff" stroke="#0f9d8f" stroke-width="3"/><circle cx="32" cy="32" r="23.5" fill="none" stroke="#0f9d8f" stroke-width="1"/><text x="32" y="34" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="16" fill="#0f9d8f">ISO</text><text x="32" y="46" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="9" letter-spacing="1" fill="#0f9d8f">9001</text></svg>',t:'ISO 9001',s:'품질경영시스템 인증'},
 {i:'<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="29" fill="#fff" stroke="#2f9e44" stroke-width="3"/><circle cx="32" cy="32" r="23.5" fill="none" stroke="#2f9e44" stroke-width="1"/><text x="32" y="34" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="16" fill="#2f9e44">ISO</text><text x="32" y="46" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="8.5" letter-spacing=".5" fill="#2f9e44">14001</text></svg>',t:'ISO 14001',s:'환경경영시스템 인증'},
 {i:'<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="29" fill="#fff" stroke="#2f7fd0" stroke-width="3"/><text x="32" y="30" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="12.5" fill="#2f7fd0">HACCP</text><path d="M17 37 Q32 51 47 37" fill="none" stroke="#f08c1d" stroke-width="3.4" stroke-linecap="round"/></svg>',t:'위생안전 인증',s:'식품위생법 준수'},
 {i:'<svg viewBox="0 0 64 64"><rect x="15" y="8" width="34" height="48" rx="3" fill="#fff" stroke="#2f6fd6" stroke-width="2.4"/><line x1="21" y1="19" x2="43" y2="19" stroke="#2f6fd6" stroke-width="2.2"/><line x1="21" y1="26" x2="43" y2="26" stroke="#c2d4f0" stroke-width="2"/><line x1="21" y1="32" x2="37" y2="32" stroke="#c2d4f0" stroke-width="2"/><line x1="21" y1="38" x2="40" y2="38" stroke="#c2d4f0" stroke-width="2"/><circle cx="40" cy="45" r="7.5" fill="none" stroke="#e23b3b" stroke-width="2.2"/><path d="M37 45l2 2 4-4" fill="none" stroke="#e23b3b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',t:'시험성적서',s:'내구성 / 내열성 / 내식성'},
 {i:'<svg viewBox="0 0 64 64"><path d="M25 6l5 26-8-2z" fill="#cdd8ec"/><path d="M39 6l-5 26 8-2z" fill="#a9b8d6"/><circle cx="32" cy="42" r="17" fill="#f4c430" stroke="#d9a520" stroke-width="2.5"/><circle cx="32" cy="42" r="11" fill="none" stroke="#e6b82e" stroke-width="1.6"/><path d="M32 33l2.6 5.3 5.8.6-4.3 3.9 1.3 5.7-5.4-3-5.4 3 1.3-5.7-4.3-3.9 5.8-.6z" fill="#fff7dd"/></svg>',t:'디자인 등록',s:'디자인 등록증'}
];
const TSTATS=[
 // 260731) '206개 모델' 통계 제거 — 승연 지시. 그리드가 repeat(4,1fr) 로 고정이라
 // 칸을 비우면 레이아웃이 깨진다. 모델 총계 대신 검증된 부품 구성 수로 대체한다.
 {t:20,suf:'년+',l:'후드 전문 생산'},{t:51,suf:'종',l:'정품 부품 구성'},
 {t:30,suf:'개국+',l:'수출 및 납품'},{t:5000,suf:'+',l:'설치 현장',comma:1}
];
const SITES=[
 {n:1,flag:'🇯🇵',loc:'일본 도쿄',d:'대형 외식 프랜차이즈'},
 {n:2,flag:'🇦🇺',loc:'호주 시드니',d:'레스토랑 설치 현장'},
 {n:3,flag:'🇺🇸',loc:'미국 LA',d:'한식당 설치 현장'},
 {n:4,flag:'🇻🇳',loc:'베트남 하노이',d:'바비큐 레스토랑'}
];
// 연혁 타임라인 (기술 기획의도 SECTION 04 — "실제 현장에서 증명되고 있습니다")
const TLINE=[
 {y:'2018',t:'와이어리스 텐션 승강 구조 개발',d:'와이어 없이 작동하는 후드 구조를 자체 개발'},
 {y:'2020',t:'핵심 기술 특허 등록',d:'텐션 승강 · 양옆태엽 구조 등 핵심 기술 특허 확보'},
 {y:'2021',t:'일본 시장 납품 시작',d:'대형 외식 프랜차이즈에 후드 공급'},
 {y:'2023',t:'호주 수출 개시',d:'해외 레스토랑 설치 현장으로 확대'},
 {y:'2025',t:'풀 라인업 체계 완성',d:'국내 최대 규모의 후드 제품군 보유'}
];
let techBuilt=false;
// ===== BRAND HISTORY (260729 회의 5.기술력 · ref: 브랜드히스토리_사진및영상) =====
const BH=[
 {no:'PART 02',en:'SWING',kr:'360° 스윙',
  lead:'설치하는 사람의 불편에서 시작된 기술',
  body:['덕트를 설치할 때마다 후드의 중심을 정확하게 맞추는 일은 쉽지 않았습니다.',
        '또한 고정형 후드는 청소나 유지보수를 위해 테이블을 옮겨야 하는 불편도 있었습니다.'],
  q:'조금 더 편하게 설치하고,<br>조금 더 편하게 관리할 수는 없을까?',
  res:'그 고민 끝에 자연스럽게 중심을 찾아주는 <b>360° SWING</b> 기술이 탄생했습니다.',
  tail:'설치는 더 정확하게. 관리는 더 편리하게.',
  vid:'bh/v-swing.mp4',vcap:'360° SWING · 제품 전체 영상',
  ph:[['bh/p2-1.jpg','360° 스윙 적용 현장'],['bh/p2-2.jpg','360° 스윙 후드 상세']]},
 {no:'PART 03',en:'TENSION',kr:'와이어 없는 상하 작동',
  lead:'와이어에 대한 불안에서 시작된 기술',
  body:['현장에서 가장 자주 들었던 이야기는 바로 와이어에 대한 불안이었습니다.',
        '“언제 끊어질지 몰라 불안하다”, “교체하기가 까다롭다”라는 현장의 목소리.'],
  q:'와이어 없이 상하 작동을<br>구현할 수는 없을까?',
  res:'오랜 연구 끝에 와이어 단선 걱정을 근본적으로 해결한 독자적인 <b>TENSION</b> 기술을 탄생시켰습니다.',
  tail:'',
  vid:'bh/v-tension.mp4',vcap:'TENSION · 상하 작동 영상',
  ph:[['bh/p3-1.jpg','텐션 방식 후드']]},
 {no:'PART 04',en:'DUAL DIECASTING',kr:'외장형 양옆태엽형',
  lead:'사용하는 사람의 입장에서 다시 생각한 기술',
  body:['부드러운 작동감은 유지하면서도, 관리와 교체는 더 쉬울 수 없을까.',
        '사용하는 사람의 입장에서 다시 생각했습니다.'],
  q:'와이어를 외부로 꺼내면,<br>상태 확인도 쉬워지고 교체도 훨씬 편해지지 않을까?',
  res:'그 결과, 부드러운 작동감은 유지하면서 유지보수의 편의성을 극대화한 <b>DUAL DIECASTING</b>(외장형 양옆태엽형) 기술을 개발했습니다.',
  tail:'',
  vid:'bh/v-dual.mp4',vcap:'DUAL DIECASTING · 상하 작동 영상',
  ph:[['bh/p4-1.jpg','외장형 양옆태엽 후드']]}
];
function renderBH(){
  const el=document.getElementById('bs-chs'); if(!el)return;
  el.innerHTML=BH.map((b,i)=>{
    // giant ghost numeral behind the chapter (branding-page device, not a blog heading)
    const num=(b.no.match(/\d+/)||[''])[0];
    const shots=b.ph.map(p=>`<figure><img loading="lazy" src="${p[0]}" alt="${p[1]}"></figure>`).join('');
    return `<section class="bs-ch${i%2?' dark rev':''}">
      <span class="bs-ghost" aria-hidden="true">${num}</span>
      <div class="wrap">
        <div class="bs-media${b.ph.length?'':' solo'} reveal">
          <div class="bs-vid"><video src="${b.vid}" muted loop playsinline preload="metadata" autoplay></video>
            <span class="bs-vcap"><i></i>${b.vcap}</span></div>
          ${b.ph.length?`<div class="bs-shots">${shots}</div>`:''}
        </div>
        <div class="bs-copy reveal">
          <div class="bs-no"><i></i>${b.no}</div>
          <div class="bs-en">${b.en}</div>
          <div class="bs-kr">${b.kr}</div>
          <div class="bs-lead">${b.lead}</div>
          <div class="bs-body">${b.body.map(t=>`<p>${t}</p>`).join('')}</div>
          <div class="bs-q">“${b.q}”</div>
          <p class="bs-res">${b.res}</p>
          ${b.tail?`<div class="bs-tail">${b.tail}</div>`:''}
        </div>
      </div></section>`;
  }).join('');
  bhAutoPlay();
}
// play the demo clips only while they are on screen (CPU/battery friendly)
function bhAutoPlay(){
  const vs=document.querySelectorAll('#bs-chs video');
  if(!('IntersectionObserver'in window)){vs.forEach(v=>{const p=v.play();if(p&&p.catch)p.catch(function(){});});return;}
  const io=new IntersectionObserver(es=>es.forEach(e=>{
    if(e.isIntersecting){const p=e.target.play();if(p&&p.catch)p.catch(function(){});}
    else e.target.pause();
  }),{threshold:.2});
  vs.forEach(v=>io.observe(v));
}
function renderTech(){
  if(techBuilt)return; techBuilt=true;
  /* r32 / r3 덱 s6 — 「'자세히 보기' 지워주고 **모달도 삭제**」.
     r30 에서 카드 앞면의 .tf-more(「자세히 보기 →」)만 지웠는데, 카드 자체가
     role="button" + onclick="openFirst(i)" 라 아무 데나 눌러도 모달이 그대로 떴다.
     → 클릭·키보드 진입점과 button 시맨틱을 전부 뺀다. 이제 카드는 그냥 정보 타일이다.
     ★ openFirst()·#fmask·CERTS 등 아래 코드는 지우지 않는다 — 호출만 안 되면 무해하고,
       승연이 「역시 모달은 두자」 하면 이 한 줄만 되돌리면 된다.
     ★ 커서·hover 들썩임은 usung-r32.css 가 죽인다(여기서 클래스만 남긴다). */
  /* ── r66) 사진 4장을 관리자가 바꿀 수 있게 한다 ──────────────────────────────
     ★ `FIRSTS[i].src`(=proto_assets/tf_*.png)를 **덮어쓰지 않는다.** 새 자리
       `/tech/first<N>.png` 를 먼저 보고, 없으면 원본으로 떨어진다(r63 로고와 같은 형태).
       → **그 파일 하나 지우는 게 곧 원상복구**이고, 원본은 리포에 그대로 산다.
       착수 시점 실측 `GET /tech/first1.png` → **404** = 안 올린 지금이 정상 동작이다.
     ★★ `onerror` 를 **함수 호출로 쓰지 않는다** — 이 스크립트가 로드되기 전에 404 가 나면
       이름 있는 함수는 ReferenceError 만 내고 대체가 안 된다(r63 `0_onerror_자족적`).
       속성 안에서 자족적으로 끝낸다. 사슬 = 새 파일 → 원본 → (원본도 실패하면) 숨김.
       ★ 첫 줄에서 `this.onerror` 를 **먼저 갈아끼운다** — 안 그러면 원본도 404 일 때
         같은 핸들러가 다시 돌아 `src` 를 계속 원본으로 되돌리는 무한 루프가 된다.
     ★ 폭 상한은 `usung-r66.css` 가 잡는다 — 종횡비가 제각각인 사진이 올라와도
       카드 글자를 덮지 않는다(승연 「플레이스 홀더는 사이즈 동일하게」). */
  document.getElementById('th-first').innerHTML=FIRSTS.map((f,i)=>
    `<div class="tf-card reveal r32-nolink" style="transition-delay:${i*90}ms">
      <div class="tf-txt">
        <span class="tf-badge">국내 최초</span>
        <div class="tf-title">${f.t}</div><div class="tf-desc">${f.d}</div>
      </div>
      <img class="tf-hood" src="/tech/first${i+1}.png" alt="${f.t}"
           onerror="this.onerror=function(){this.style.opacity=0};this.src='${f.src}'">
    </div>`).join('');
  renderBH();
  document.getElementById('cert-row').innerHTML=CERTS.map(c=>
    `<div class="cert-item"><div class="cert-thumb"><img src="certs/cert${c.n}.png" alt="${c.c}" loading="lazy"></div>
      <div class="cert-cap">${c.c}</div></div>`).join('');
  document.getElementById('th-badges').innerHTML=CBADGES.map(b=>
    `<div class="cb"><div class="cb-ico">${b.i}</div><div class="cb-t">${b.t}</div><div class="cb-s">${b.s}</div></div>`).join('');
  document.getElementById('th-stats').innerHTML=TSTATS.map(s=>
    `<div class="st-c"><div class="st-n" data-t="${s.t}"${s.comma?' data-comma="1"':''}><span class="v">0</span><em>${s.suf}</em></div>
      <div class="st-l">${s.l}</div></div>`).join('');
  document.getElementById('site-grid').innerHTML=SITES.map(s=>
    `<div class="site-c"><div class="site-ph"><img src="sites/site${s.n}.png" alt="${s.loc}" loading="lazy"></div>
      <div class="site-meta"><div class="site-head"><span class="site-flag">${s.flag}</span><span class="site-loc">${s.loc}</span></div><div class="site-desc">${s.d}</div></div>
    </div>`).join('');
}
/* ===== 국내최초 → 해당 제품으로 이동 (interactive product link) =====
   each innovation card maps to a real product model (key) inside a category (cat);
   clicking navigates to the category page and opens that product's detail modal. */
function firstToProduct(i){
  const f=FIRSTS[i]; if(!f) return;
  const hasModel=f.key&&MODELS.some(m=>m.key===f.key);
  if(f.cat) goCat(f.cat); else goMain();   // land in the product context
  if(hasModel) openModel(f.key,0);          // open the specific product detail
}
/* ===== 국내최초 상세 모달 (long-form) ===== */
function openFirst(i){
  const f=FIRSTS[i]; if(!f) return;
  document.getElementById('fm-title').textContent=f.t;
  document.getElementById('fm-sub').textContent=f.sub||'';
  document.getElementById('fm-desc').textContent=f.body||'';
  document.getElementById('fm-points').innerHTML=(f.points||[]).map(p=>
    `<li><div class="ph">${p.h}</div><div class="pp">${p.p}</div></li>`).join('');
  const note=document.getElementById('fm-note');
  note.textContent=f.note||''; note.style.display=f.note?'':'none';
  // secondary CTA → jump to the matching product detail; hide if no model mapped
  const cta=document.getElementById('fm-cta');
  const hasModel=f.key&&MODELS.some(m=>m.key===f.key);
  cta.style.display=hasModel?'':'none';
  cta.onclick=function(){closeFirst();firstToProduct(i);};
  const modal=document.querySelector('#fmask .fmodal');
  modal.classList.add('fm-enter');            // set hidden pre-state before showing
  document.getElementById('fmask').classList.add('on');
  document.body.style.overflow='hidden';
  document.querySelector('#fmask .fm-body').scrollTop=0;
  void modal.offsetWidth;                      // commit pre-state, then release to run the entrance transition
  setTimeout(()=>modal.classList.remove('fm-enter'),20);
}
function closeFirst(){document.getElementById('fmask').classList.remove('on');document.body.style.overflow='';}
function techCountUp(){
  document.querySelectorAll('#th-stats .st-n').forEach(el=>{
    const t=+el.dataset.t, comma=el.dataset.comma==='1', v=el.querySelector('.v'); let s=null;
    function step(ts){if(s===null)s=ts;const p=Math.min((ts-s)/1400,1),eased=1-Math.pow(1-p,3),cur=Math.round(t*eased);
      v.textContent=comma?cur.toLocaleString():cur; if(p<1)requestAnimationFrame(step); else v.textContent=comma?t.toLocaleString():t;}
    requestAnimationFrame(step);
  });
}
let techObs=null, techStatsDone=false;
function setupTechReveal(){
  if(!('IntersectionObserver'in window)){document.querySelectorAll('#v-tech .reveal').forEach(el=>el.classList.add('in'));if(!techStatsDone){techStatsDone=true;techCountUp();}return;}
  if(techObs)techObs.disconnect();
  techObs=new IntersectionObserver((ents,obs)=>{
    ents.forEach(e=>{if(e.isIntersecting||e.boundingClientRect.top<0){e.target.classList.add('in');obs.unobserve(e.target);}});
  },{rootMargin:'0px 0px -8% 0px',threshold:.08});
  document.querySelectorAll('#v-tech .reveal:not(.in)').forEach(el=>techObs.observe(el));
  const stats=document.getElementById('th-stats');
  if(stats&&!techStatsDone){
    const so=new IntersectionObserver((ents,o)=>{ents.forEach(e=>{if(e.isIntersecting){techStatsDone=true;techCountUp();o.disconnect();}});},{threshold:.3});
    so.observe(stats);
  }
}
function goTech(){showView('v-tech');setNav('nav-tech');window.scrollTo(0,0);renderTech();setupTechReveal();}
