/* usung-r8-data.js — r8 카탈로그 이식 모듈 (공통 데이터 · 부품 사전 · 아이콘)
 * GENERATED by build_graft.py from _proto_catalog_r8.html (JS1 1-151).
 * Do not edit by hand — edit the prototype and rebuild.
 * Loads as a classic script; shares global scope with the other r8 modules.
 */

const R8_IMG='https://usung-ace.vercel.app/products/final/';
// 260729 회의: 카카오톡 채널은 운영하지 않음 — 모든 문의 동선은 대표전화 하나로 통일
const TEL_NO='1588-9123', TEL_LABEL='대표전화';
function telHref(){return 'tel:'+TEL_NO.replace(/[^0-9+]/g,'');}
// fill every element that carries data-tel / #cta-tel with the 대표전화 link
function applyTel(){
  const cta=document.getElementById('cta-tel');
  if(cta){cta.href=telHref();cta.textContent='대표전화 '+TEL_NO+' 상담하기 →';}
  document.querySelectorAll('[data-tel]').forEach(function(a){a.href=telHref();});
}
// Auto-trim transparent margins so every product cutout centers identically (Req: consistent 10px gap).
function trimImg(img){
  if(!img||img.dataset.tr==='1')return; img.dataset.tr='1';
  try{
    const w=img.naturalWidth,h=img.naturalHeight; if(!w||!h)return;
    const cv=document.createElement('canvas');cv.width=w;cv.height=h;
    const cx=cv.getContext('2d');cx.drawImage(img,0,0);
    const d=cx.getImageData(0,0,w,h).data;
    let t=h,l=w,r=0,b=0,found=false;
    for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(d[(y*w+x)*4+3]>14){found=true;if(x<l)l=x;if(x>r)r=x;if(y<t)t=y;if(y>b)b=y;}}
    if(!found)return;
    const mw=Math.round((r-l)*.015)+1,mh=Math.round((b-t)*.015)+1;
    l=Math.max(0,l-mw);t=Math.max(0,t-mh);r=Math.min(w-1,r+mw);b=Math.min(h-1,b+mh);
    const tw=r-l+1,th=b-t+1,o=document.createElement('canvas');o.width=tw;o.height=th;
    o.getContext('2d').drawImage(cv,l,t,tw,th,0,0,tw,th);
    img.src=o.toDataURL('image/png');
  }catch(e){}
}
const R8_CATS=['갤럭시','LED조명','파이프','후레쉬볼','코브라후드'];
const META={
 '갤럭시':{en:'GALAXY SERIES',kr:'갤럭시 시리즈',desc:'디자인과 기능을 모두 갖춘 유성에이스의 대표 라인업',feats:['다양한 유형','태엽 구조','다양한 색상'],rep:'gal001',banner:'proto_assets/cat_gal.jpg'},
 'LED조명':{en:'LED SERIES',kr:'LED 조명',desc:'고급스러운 분위기를 완성하는 LED 조명 라인업',feats:['LED 조명','고급 디자인','다양한 옵션'],rep:'led006',banner:'proto_assets/cat_led.jpg'},
 '파이프':{en:'PIPE SERIES',kr:'파이프 시리즈',desc:'다양한 길이와 구조로 선택 가능한 파이프 라인업',feats:['다양한 길이','견고한 구조','다양한 색상'],rep:'pipe001',banner:'proto_assets/cat_pipe.jpg'},
 '후레쉬볼':{en:'FRESHBALL SERIES',kr:'후레쉬볼 시리즈',desc:'유연한 구조와 부드러운 작동이 돋보이는 후레쉬볼 라인업',feats:['유연한 구조','부드러운 작동','다양한 색상'],rep:'ball001',banner:'proto_assets/cat_ball.jpg'},
 '코브라후드':{en:'DOWNDRAFT · COBRA',kr:'하향식 후드',desc:'공간 효율을 높이는 하향식·코브라 후드 라인업',feats:['안전한 방식','세련된 디자인','다양한 색상'],rep:'cobra001',banner:'proto_assets/cat_cobra.jpg'}
};
// 마감(finish) 실제 값 기준 · 상호배타 · 정확 일치. (모던=매끈메탈 / 클래식=함마톤 / 프리미엄=도금 / 레트로=진한·컬러)
const STYLES={
 '모던':['스텐도금','스텐도장','헤어라인','크롬'],
 '클래식':['동함마','실버함마','황색함마','흰색함마'],
 '프리미엄':['동도금','신주도금'],
 '레트로':['검정함마','흑도금','주황함마','초록함마','빨강','노랑']
};
// ===== feature icons (inline SVG, currentColor) =====
const SVG={
 color:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="9" cy="9" r="4"/><circle cx="15" cy="9" r="4"/><circle cx="12" cy="15" r="4"/></svg>',
 gear:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M19.1 4.9L17 7M7 17l-2.1 2.1"/></svg>',
 layers:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 3l9 5-9 5-9-5 9-5z"/><path d="M3 13l9 5 9-5"/></svg>',
 bulb:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-4 10.5c.7.7 1 1.3 1 2.5h6c0-1.2.3-1.8 1-2.5A6 6 0 0 0 12 3z"/></svg>',
 sparkle:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3z"/></svg>',
 ruler:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="3" y="8" width="18" height="8" rx="1"/><path d="M7 8v3M11 8v4M15 8v3M19 8v4"/></svg>',
 wave:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M3 12c2-3 4-3 6 0s4 3 6 0 4-3 6 0"/><path d="M3 7c2-3 4-3 6 0s4 3 6 0 4-3 6 0" opacity=".45"/></svg>',
 shield:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l7 3v5c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6l7-3z"/><path d="M9 12l2 2 4-4"/></svg>',
 rotate:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7"/><path d="M21 4v4h-4"/></svg>',
 grid:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><rect x="4" y="4" width="7" height="7" rx="1"/><rect x="13" y="4" width="7" height="7" rx="1"/><rect x="4" y="13" width="7" height="7" rx="1"/><rect x="13" y="13" width="7" height="7" rx="1"/></svg>',
 diamond:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M6 3h12l3 6-9 12L3 9l3-6z"/><path d="M3 9h18M9 3l3 6 3-6M12 21l-3-12M12 21l3-12"/></svg>',
 clock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>'
};
function iconFor(s){
  s=String(s||'');
  if(/색상|컬러|도금|크롬/.test(s))return SVG.color;
  if(/태엽|견고|구조/.test(s))return SVG.gear;
  if(/유형|옵션|다양/.test(s))return SVG.layers;
  if(/LED|조명|등/.test(s))return SVG.bulb;
  if(/길이/.test(s))return SVG.ruler;
  if(/유연|부드/.test(s))return SVG.wave;
  if(/안전/.test(s))return SVG.shield;
  if(/작동|회전/.test(s))return SVG.rotate;
  if(/디자인|세련|고급|프리미엄/.test(s))return SVG.sparkle;
  if(/모던/.test(s))return SVG.grid;
  if(/클래식/.test(s))return SVG.diamond;
  if(/레트로/.test(s))return SVG.clock;
  return SVG.sparkle;
}

// ===== R8_PARTS (부품 및 옵션) — 48 real cutouts, {nm:name, sp:size/spec} =====
const PART_BASE='https://usung-ace.vercel.app/parts/';
// 260730 crosscheck) 서버 부품 이미지(p01~p48)를 원본 「부품갤러리」 파일명과 1:1 대조해 전면 교정.
// p01~p45 = 부품갤러리 45종(파일명 가나다순)과 정확히 일치 확인. p46~p48은 원본 미제공 → 형상 기준 추정.
const R8_PARTS={
 p01:{nm:'FVD 방화댐퍼',sp:'크롬'}, p02:{nm:'VD 풍량조절댐퍼',sp:'크롬'}, p03:{nm:'반후지',sp:'크롬'},
 p04:{nm:'사각 측향모터',sp:''}, p05:{nm:'원형 상향모터',sp:''}, p06:{nm:'원형 측향모터',sp:''},
 p07:{nm:'천정형 캡',sp:''}, p08:{nm:'측향',sp:''}, p09:{nm:'5단 유지망',sp:''},
 p10:{nm:'등링',sp:''}, p11:{nm:'빠찌링',sp:''}, p12:{nm:'사각 태엽감속기',sp:''},
 p13:{nm:'속링',sp:''}, p14:{nm:'철제 태엽감속기',sp:''}, p15:{nm:'FVD 휴즈',sp:''}, p16:{nm:'휴즈핀',sp:''},
 p17:{nm:'1중망',sp:''}, p18:{nm:'8단 유지망',sp:''}, p19:{nm:'갓 기름받이',sp:''}, p20:{nm:'기름받이 망',sp:''},
 p21:{nm:'기름받이 속',sp:''}, p22:{nm:'롱망',sp:''}, p23:{nm:'기름받이',sp:'150Ø'}, p24:{nm:'일체형 기름받이',sp:''},
 p25:{nm:'나팔',sp:'150Ø'}, p26:{nm:'갓 + 나팔',sp:'210Ø'}, p27:{nm:'갓 + 나팔',sp:'250Ø'},
 p28:{nm:'속레일',sp:''}, p29:{nm:'연결캡',sp:'상부'}, p30:{nm:'연결캡',sp:'하부'}, p31:{nm:'일자형 기름받이',sp:''},
 p32:{nm:'티구찌',sp:''}, p33:{nm:'갓',sp:'210Ø 크롬'}, p34:{nm:'갓',sp:'250Ø'}, p35:{nm:'갓',sp:'200Ø (304용)'},
 p36:{nm:'갓 + 나팔',sp:'320Ø'}, p37:{nm:'갓 + 나팔',sp:'350Ø'}, p38:{nm:'갓',sp:'450Ø'}, p39:{nm:'갓',sp:'520Ø'},
 p40:{nm:'자바라 하부봉대',sp:''}, p41:{nm:'후레쉬볼',sp:'검정'}, p42:{nm:'후레쉬볼',sp:'동'},
 p43:{nm:'후레쉬볼',sp:'신주'}, p44:{nm:'후레쉬볼',sp:'은'}, p45:{nm:'후레쉬볼 커버',sp:'상 + 하'},
 p46:{nm:'FVD 방화댐퍼',sp:'스텐'}, p47:{nm:'VD 풍량조절댐퍼',sp:'스텐'}, p48:{nm:'반후지',sp:'스텐'}
};
// R3: parts whose source subject is very small (≤130px) → most upscaled/pixelated → extra ~40% shrink
const PART_LOWRES=new Set(['p09','p10','p11','p15','p29','p30','p31']);
// representative parts shown per category (image16: 대표 예시)
const CATPARTS={
 '갤럭시':['p12','p14','p13','p28','p11','p32','p09','p18','p21','p05','p06','p26'],
 'LED조명':['p19','p38','p39','p33','p36','p37','p10','p20','p05','p02','p32','p22'],
 '파이프':['p03','p48','p08','p07','p01','p46','p02','p47','p15','p16','p25','p22'],
 '후레쉬볼':['p41','p42','p43','p44','p45','p40','p31','p24','p09','p18','p07','p25'],
 '코브라후드':['p25','p07','p01','p02','p05','p06','p09','p18','p35','p34','p29','p30']
};
// 부품 전체 페이지 — 규격·용도별 그룹 (48종)
const PART_GROUPS=[
 {t:'구동부 · 태엽감속기',ids:['p12','p14','p13','p11','p28','p32','p10']},
 {t:'모터',ids:['p04','p05','p06']},
 {t:'댐퍼 · 휴즈',ids:['p01','p02','p46','p47','p15','p16']},
 {t:'후지 · 측향 · 캡 · 나팔',ids:['p03','p48','p08','p07','p29','p30','p25']},
 {t:'유지망',ids:['p09','p17','p18','p22']},
 {t:'기름받이',ids:['p19','p20','p21','p23','p24','p31']},
 {t:'갓 (Ø 규격별)',ids:['p26','p27','p33','p34','p35','p36','p37','p38','p39']},
 {t:'후레쉬볼 · 자바라',ids:['p40','p41','p42','p43','p44','p45']}
];
// part id -> group title (분류)
const PART_GROUP_OF={};
PART_GROUPS.forEach(g=>g.ids.forEach(id=>{if(!PART_GROUP_OF[id])PART_GROUP_OF[id]=g.t;}));
// part id -> categories using it (사용 제품군), derived from CATPARTS
const PART_USEDBY={};
Object.keys(CATPARTS).forEach(c=>CATPARTS[c].forEach(id=>{
  const label=(c==='코브라후드'?'하향식후드':c);
  (PART_USEDBY[id]=PART_USEDBY[id]||[]).push(label);
}));
// group-level descriptions for the part modal
const PART_GROUP_DESC={
 '구동부 · 태엽감속기':'후드를 부드럽게 올리고 내리는 핵심 구동부입니다. 태엽 방식으로 별도 동력 없이 안정적으로 작동합니다.',
 '모터':'배기 성능을 좌우하는 모터 구성품입니다. 설치 방향·형태에 따라 상향·측향 모델을 선택합니다.',
 '댐퍼 · 휴즈':'풍량 조절과 방화 안전을 담당하는 부품입니다. 화재 시 휴즈가 작동해 배기구를 차단합니다.',
 '후지 · 측향 · 캡 · 나팔':'배기 연결·마감을 위한 구성품입니다. 규격에 맞춰 배관과 연결됩니다.',
 '유지망':'기름·이물질을 걸러 배기 효율과 위생을 유지하는 필터망입니다. 단수·규격별로 선택합니다.',
 '기름받이':'조리 시 발생하는 기름을 모아 관리하는 부품입니다. 분리·세척이 가능합니다.',
 '갓 (Ø 규격별)':'후드 하부를 마감하는 갓입니다. 공간과 배기 규격에 맞춰 Ø 사이즈를 선택합니다.',
 '후레쉬볼 · 자바라':'신축 자바라와 후레쉬볼 구성품입니다. 유연한 구조로 다양한 설치 높이에 대응합니다.'
};
let ITEMS=[], MODELS=[], byCatM={}, curModel=null, curIdx=0, activeStyle=null;
// product name with its own finish token removed → identifies the physical product (shape)
function baseOf(it){return (it.finish?it.name.split(it.finish).join(''):it.name).replace(/\s+/g,' ').trim();}
// real color/finish label: skip structural labels (cat/mid/grp); many 도금 rows store 마감==중분류,
// so fall back to the last meaningful tag (the actual plating color) or the last name token
function colorOf(it){
  const struct=new Set([it.cat,it.mid,it.grp,'']);
  if(it.finish && !struct.has(it.finish)) return it.finish;
  const tg=it.tags||[];
  for(let i=tg.length-1;i>=0;i--){ if(!struct.has(tg[i])) return tg[i]; }
  const toks=(it.name||'').split(/\s+/).filter(Boolean);
  return toks.length?toks[toks.length-1]:'';
}
