const productCatalog = [
  { img: "products/p001_01갤럭시B_150Ø스파이럴_내부태엽_검정함마스파이얼.jpg", name: "갤럭시B 150Ø스파이럴 내부태엽 검정함마스파이얼", cat: "갤럭시 B타입", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p002_01갤럭시B_150Ø스파이럴_내부태엽_동함마스파이얼.jpg", name: "갤럭시B 150Ø스파이럴 내부태엽 동함마스파이얼", cat: "갤럭시 B타입", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p003_01갤럭시B_150Ø스파이럴_내부태엽_실버함마스파이얼.jpg", name: "갤럭시B 150Ø스파이럴 내부태엽 실버함마스파이얼", cat: "갤럭시 B타입", finish: "실버함마", pipe: "스파이얼" },
  { img: "products/p004_01갤럭시B_150Ø스파이럴_내부태엽_황색함마.jpg", name: "갤럭시B 150Ø스파이럴 내부태엽 황색함마", cat: "갤럭시 B타입", finish: "노랑함마", pipe: "스파이얼" },
  { img: "products/p005_01갤럭시B_150Ø스파이럴_양옆태엽_동함마스파이얼.jpg", name: "갤럭시B 150Ø스파이럴 양옆태엽 동함마스파이얼", cat: "갤럭시 B타입", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p006_01갤럭시B_304스텐_내부태엽_헤어라인.jpg", name: "갤럭시B 304스텐 내부태엽 헤어라인", cat: "갤럭시 B타입", finish: "헤어라인, 304스텐", pipe: "" },
  { img: "products/p007_01갤럭시B_304스텐_양옆태엽_파이프_동.jpg", name: "갤럭시B 304스텐 양옆태엽(파이프) 동", cat: "갤럭시 B타입", finish: "304스텐", pipe: "" },
  { img: "products/p008_01갤럭시B_304스텐_양옆태엽_파이프_신주.jpg", name: "갤럭시B 304스텐 양옆태엽(파이프) 신주", cat: "갤럭시 B타입", finish: "신주, 304스텐", pipe: "" },
  { img: "products/p009_01갤럭시B_304스텐_양옆태엽_파이프_크롬.jpg", name: "갤럭시B 304스텐 양옆태엽(파이프) 크롬", cat: "갤럭시 B타입", finish: "크롬, 304스텐", pipe: "" },
  { img: "products/p010_01갤럭시B_304스텐_양옆태엽_파이프_헤어라인.jpg", name: "갤럭시B 304스텐 양옆태엽(파이프) 헤어라인", cat: "갤럭시 B타입", finish: "헤어라인, 304스텐", pipe: "" },
  { img: "products/p011_01갤럭시B_304스텐_양옆태엽_파이프_흑도금.jpg", name: "갤럭시B 304스텐 양옆태엽(파이프) 흑도금", cat: "갤럭시 B타입", finish: "흑도금, 304스텐", pipe: "" },
  { img: "products/p012_01갤럭시B_304스텐_양옆태엽_헤드_헤어라인.jpg", name: "갤럭시B 304스텐 양옆태엽(헤드) 헤어라인", cat: "갤럭시 B타입", finish: "헤어라인, 304스텐", pipe: "" },
  { img: "products/p013_02_304스텐_헤드FVD_양옆태엽_헤드.jpg", name: "304스텐(헤드FVD) 양옆태엽(헤드)", cat: "양옆태엽[BEST]", finish: "304스텐", pipe: "" },
  { img: "products/p014_02유성에이스_304스텐_헤드FVD_양옆태엽_파이프.jpg", name: "스텐(헤드FVD) 양옆태엽(파이프)", cat: "양옆태엽[BEST]", finish: "304스텐", pipe: "" },
  { img: "products/p015_03갤럭시C_150Ø5단유지망_내부태엽_검정함마.jpg", name: "갤럭시C 150Ø5단유지망 내부태엽 검정함마", cat: "갤럭시 C타입 원통필터", finish: "검정함마", pipe: "" },
  { img: "products/p016_03갤럭시C_150Ø5단유지망_내부태엽_동함마.jpg", name: "갤럭시C 150Ø5단유지망 내부태엽 동함마", cat: "갤럭시 C타입 원통필터", finish: "동함마", pipe: "" },
  { img: "products/p017_03갤럭시C_150Ø5단유지망_내부태엽_실버함마.jpg", name: "갤럭시C 150Ø5단유지망 내부태엽 실버함마", cat: "갤럭시 C타입 원통필터", finish: "실버함마", pipe: "" },
  { img: "products/p018_03갤럭시C_150Ø5단유지망_내부태엽_황색함마.jpg", name: "갤럭시C 150Ø5단유지망 내부태엽 황색함마", cat: "갤럭시 C타입 원통필터", finish: "노랑함마", pipe: "" },
  { img: "products/p019_09_150Ø_스텐도금_FVD_텐션_신주.jpg", name: "150Ø 스텐도금 (FVD) 텐션 신주", cat: "파이프", finish: "도금, 신주", pipe: "" },
  { img: "products/p020_09_150Ø_스텐도금_반후지_텐션_동.jpg", name: "150Ø 스텐도금 (반후지) 텐션 동", cat: "파이프", finish: "도금", pipe: "" },
  { img: "products/p021_09_150Ø_스텐도금_반후지_텐션_크롬.jpg", name: "150Ø 스텐도금 (반후지) 텐션 크롬", cat: "파이프", finish: "도금, 크롬", pipe: "" },
  { img: "products/p022_09_150Ø_스텐도금_반후지_텐션_헤어라인.jpg", name: "150Ø 스텐도금 (반후지) 텐션 헤어라인", cat: "파이프", finish: "도금, 헤어라인", pipe: "" },
  { img: "products/p023_09_150Ø_스텐도금_반후지_텐션_흑도금.jpg", name: "150Ø 스텐도금 (반후지) 텐션 흑도금", cat: "파이프", finish: "흑도금", pipe: "" },
  { img: "products/p024_09_150Ø_스텐도장_FVD_텐션_실버함마.jpg", name: "150Ø 스텐도장 (FVD) 텐션 실버함마", cat: "파이프", finish: "실버함마", pipe: "" },
  { img: "products/p025_09_150Ø_스텐도장_FVD_텐션_주황함마.jpg", name: "150Ø 스텐도장 (FVD) 텐션 주황함마", cat: "파이프", finish: "주황함마", pipe: "" },
  { img: "products/p026_09_150Ø_스텐도장_반후지_텐션_검정함마.jpg", name: "150Ø 스텐도장 (반후지) 텐션 검정함마", cat: "파이프", finish: "검정함마", pipe: "" },
  { img: "products/p027_09_150Ø_스텐도장_반후지_텐션_동함마.jpg", name: "150Ø 스텐도장 (반후지) 텐션 동함마", cat: "파이프", finish: "동함마", pipe: "" },
  { img: "products/p028_10_125Ø_FVD_텐션_스텐도금_크롬.jpg", name: "125Ø(FVD) 텐션 스텐도금 크롬", cat: "파이프", finish: "도금, 크롬", pipe: "" },
  { img: "products/p029_10_125Ø_반후지_텐션_동.jpg", name: "125Ø(반후지) 텐션 동", cat: "파이프", finish: "동", pipe: "" },
  { img: "products/p030_10_125Ø_반후지_텐션_스텐도금_신주.jpg", name: "125Ø(반후지) 텐션 스텐도금 신주", cat: "파이프", finish: "도금, 신주", pipe: "" },
  { img: "products/p031_10_125Ø_반후지_텐션_스텐도금_헤어라인.jpg", name: "125Ø(반후지) 텐션 스텐도금 헤어라인", cat: "파이프", finish: "도금, 헤어라인", pipe: "" },
  { img: "products/p032_10_125Ø_반후지_텐션_스텐도금_흑도금.jpg", name: "125Ø(반후지) 텐션 스텐도금 흑도금", cat: "파이프", finish: "흑도금", pipe: "" },
  { img: "products/p033_11.jpg", name: "11", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p034_14_125Ø_반후지_스윙텐션_은스텐파이프210Ø갓.jpg", name: "125Ø(반후지) 스윙텐션 은스텐파이프210Ø갓", cat: "파이프", finish: "은", pipe: "스텐파이프" },
  { img: "products/p035_14_125Ø_반후지_텐션_스텐도장_검정함마.jpg", name: "125Ø(반후지) 텐션 스텐도장 검정함마", cat: "파이프", finish: "검정함마", pipe: "" },
  { img: "products/p036_14_125Ø_반후지_텐션_스텐도장_동함마.jpg", name: "125Ø(반후지) 텐션 스텐도장 동함마", cat: "파이프", finish: "동함마", pipe: "" },
  { img: "products/p037_14_125Ø_반후지_텐션_스텐도장_실버함마.jpg", name: "125Ø(반후지) 텐션 스텐도장 실버함마", cat: "파이프", finish: "실버함마", pipe: "" },
  { img: "products/p038_14_125Ø_반후지_텐션_스텐도장_주황함마.jpg", name: "125Ø(반후지) 텐션 스텐도장 주황함마", cat: "파이프", finish: "주황함마", pipe: "" },
  { img: "products/p039_15_FVD_주황함마_스파이얼.jpg", name: "FVD.주황함마 스파이얼", cat: "스파이얼", finish: "주황함마", pipe: "스파이얼" },
  { img: "products/p040_15_FVD실버함마_스파이얼.jpg", name: "FVD실버함마 스파이얼", cat: "스파이얼", finish: "실버함마", pipe: "스파이얼" },
  { img: "products/p041_15_150Ø_반후지_텐션_스파이얼_검정함마.jpg", name: "150Ø(반후지) 텐션 스파이얼 검정함마", cat: "스파이얼", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p042_15_150Ø_반후지_텐션_스파이얼_동함마.jpg", name: "150Ø(반후지) 텐션 스파이얼 동함마", cat: "스파이얼", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p043_16.jpg", name: "16", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p044_17.jpg", name: "17", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p045_18.jpg", name: "18", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p046_18_125Ø_반후지_스윙텐션_스파이얼_동함마210Ø갓.jpg", name: "125Ø(반후지) 스윙텐션 스파이얼 동함마210Ø갓", cat: "스파이얼", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p047_18_125Ø_FVD_텐션_스파이얼_황색함마.jpg", name: "125Ø(FVD) 텐션 스파이얼 황색함마", cat: "스파이얼", finish: "노랑함마", pipe: "스파이얼" },
  { img: "products/p048_18_125Ø_반후지_텐션_스파이얼_검정함마.jpg", name: "125Ø(반후지) 텐션 스파이얼 검정함마", cat: "스파이얼", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p049_18_125Ø_반후지_텐션_스파이얼_동함마.jpg", name: "125Ø(반후지) 텐션 스파이얼 동함마", cat: "스파이얼", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p050_18_125Ø_반후지_텐션_스파이얼_실버함마.jpg", name: "125Ø(반후지) 텐션 스파이얼 실버함마", cat: "스파이얼", finish: "실버함마", pipe: "스파이얼" },
  { img: "products/p051_19.jpg", name: "19", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p052_1유성에이스_은자바라.jpg", name: "은자바라", cat: "후레쉬볼/주름관", finish: "은", pipe: "후레쉬볼" },
  { img: "products/p053_25.jpg", name: "25", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p054_26.jpg", name: "26", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p055_27.jpg", name: "27", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p056_28.jpg", name: "28", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p057_2유성에이스_동자바라.jpg", name: "동자바라", cat: "후레쉬볼/주름관", finish: "동", pipe: "후레쉬볼" },
  { img: "products/p058_3유성에이스_신주자바라.jpg", name: "신주자바라", cat: "후레쉬볼/주름관", finish: "신주", pipe: "후레쉬볼" },
  { img: "products/p059_4유성에이스_검정자바라.jpg", name: "검정자바라", cat: "후레쉬볼/주름관", finish: "", pipe: "후레쉬볼" },
  { img: "products/p060_5유성에이스_흑도금자바라.jpg", name: "흑도금자바라", cat: "후레쉬볼/주름관", finish: "흑도금", pipe: "후레쉬볼" },
  { img: "products/p061_6유성에이스_실버자바라.jpg", name: "실버자바라", cat: "후레쉬볼/주름관", finish: "", pipe: "후레쉬볼" },
  { img: "products/p062_7.jpg", name: "7", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p063_8.jpg", name: "8", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p064_9.jpg", name: "9", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p065_DSC_4680_copy.jpg", name: "DSC 4680", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p066_DSC_4683_copy.jpg", name: "DSC 4683", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p067_DSC_4692_copy.jpg", name: "DSC 4692", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p068_DSC_4697_copy.jpg", name: "DSC 4697", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p069_DSC_4708_copy.jpg", name: "DSC 4708", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p070_DSC_4714_copy.jpg", name: "DSC 4714", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p071_DSC_4723_copy.jpg", name: "DSC 4723", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p072_DSC_4726_copy.jpg", name: "DSC 4726", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p073_DSC_4734_copy.jpg", name: "DSC 4734", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p074_DSC_4754_copy.jpg", name: "DSC 4754", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p075_DSC_4760_copy.jpg", name: "DSC 4760", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p076_DSC_4763_copy.jpg", name: "DSC 4763", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p077_DSC_4770_copy.jpg", name: "DSC 4770", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p078_DSC_4774_copy.jpg", name: "DSC 4774", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p079_DSC_4778_copy.jpg", name: "DSC 4778", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p080_DSC_4783_copy.jpg", name: "DSC 4783", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p081_DSC_4787_copy.jpg", name: "DSC 4787", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p082_DSC_4790_copy.jpg", name: "DSC 4790", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p083_DSC_4796_copy.jpg", name: "DSC 4796", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p084_DSC_4801_copy.jpg", name: "DSC 4801", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p085_DSC_4805_copy.jpg", name: "DSC 4805", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p086_DSC_4809_copy.jpg", name: "DSC 4809", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p087_DSC_4813_copy.jpg", name: "DSC 4813", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p088_DSC_4820_copy.jpg", name: "DSC 4820", cat: "후레쉬볼/주름관", finish: "", pipe: "" },
  { img: "products/p089_FVD양옆태엽검정함마스텐파이프.jpg", name: "FVD양옆태엽검정함마스텐파이프", cat: "양옆태엽[BEST]", finish: "검정함마", pipe: "스텐파이프" },
  { img: "products/p090_LED350갓등신주브론즈스텐파이프.jpg", name: "LED350갓등신주브론즈스텐파이프", cat: "LED조명", finish: "신주", pipe: "스텐파이프" },
  { img: "products/p091_LED350갓등은스텐파이프.jpg", name: "LED350갓등은스텐파이프", cat: "LED조명", finish: "은", pipe: "스텐파이프" },
  { img: "products/p092_LED350둥근갓등검정함마스텐파이프.jpg", name: "LED350둥근갓등검정함마스텐파이프", cat: "LED조명", finish: "검정함마", pipe: "스텐파이프" },
  { img: "products/p093_LED350둥근갓등동스텐파이프.jpg", name: "LED350둥근갓등동스텐파이프", cat: "LED조명", finish: "", pipe: "스텐파이프" },
  { img: "products/p094_LED350둥근갓등동함마스파이얼.jpg", name: "LED350둥근갓등동함마스파이얼", cat: "LED조명", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p095_LED400파이아크릴갓등검정함마스텐파이프.jpg", name: "LED400파이아크릴갓등검정함마스텐파이프", cat: "LED조명", finish: "검정함마", pipe: "스텐파이프" },
  { img: "products/p096_LED400파이아크릴갓등동함마스텐파이프.jpg", name: "LED400파이아크릴갓등동함마스텐파이프", cat: "LED조명", finish: "동함마", pipe: "스텐파이프" },
  { img: "products/p097_LED450갓등검정함마스파이얼.jpg", name: "LED450갓등검정함마스파이얼", cat: "LED조명", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p098_LED450갓등동스텐파이프.jpg", name: "LED450갓등동스텐파이프", cat: "LED조명", finish: "", pipe: "스텐파이프" },
  { img: "products/p099_LED450갓등실버함마스텐파이프.jpg", name: "LED450갓등실버함마스텐파이프", cat: "LED조명", finish: "실버함마", pipe: "스텐파이프" },
  { img: "products/p100_LED450노랑우주선동함마스텐파이프.jpg", name: "LED450노랑우주선동함마스텐파이프", cat: "LED우주선", finish: "동함마", pipe: "스텐파이프" },
  { img: "products/p101_LED450빨강우주선검정함마스텐파이프.jpg", name: "LED450빨강우주선검정함마스텐파이프", cat: "LED우주선", finish: "검정함마", pipe: "스텐파이프" },
  { img: "products/p102_LED450우주선동스텐파이프.jpg", name: "LED450우주선동스텐파이프", cat: "LED우주선", finish: "", pipe: "스텐파이프" },
  { img: "products/p103_LED450우주선동함마스파이얼.jpg", name: "LED450우주선동함마스파이얼", cat: "LED우주선", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p104_LED450우주선스텐파이프_후레쉬볼.jpg", name: "LED450우주선스텐파이프+후레쉬볼", cat: "LED우주선", finish: "", pipe: "스텐파이프, 후레쉬볼" },
  { img: "products/p105_LED450우주선스텐파이프_후레쉬볼_접은거.jpg", name: "LED450우주선스텐파이프+후레쉬볼(접은거)", cat: "LED우주선", finish: "", pipe: "스텐파이프, 후레쉬볼" },
  { img: "products/p106_LED450우주선신주스텐파이프.jpg", name: "LED450우주선신주스텐파이프", cat: "LED우주선", finish: "신주", pipe: "스텐파이프" },
  { img: "products/p107_LED600파이갓등검정함마스파이얼.jpg", name: "LED600파이갓등검정함마스파이얼", cat: "LED조명", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p108_LED600파이갓등신주스텐파이프.jpg", name: "LED600파이갓등신주스텐파이프", cat: "LED조명", finish: "신주", pipe: "스텐파이프" },
  { img: "products/p109_LED빨강항아리등스텐파이프.jpg", name: "LED빨강항아리등스텐파이프", cat: "LED조명", finish: "", pipe: "스텐파이프" },
  { img: "products/p110_LED원형등스파이얼_스텐파이프.jpg", name: "LED원형등스파이얼+스텐파이프", cat: "LED조명", finish: "", pipe: "스파이얼, 스텐파이프" },
  { img: "products/p111_LED항아리갓등동함마스파이얼.jpg", name: "LED항아리갓등동함마스파이얼", cat: "LED조명", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p112_갤럭시A검정함마스파이얼.jpg", name: "갤럭시A검정함마스파이얼", cat: "갤럭시 A타입", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p113_갤럭시A노랑함마스파이얼.jpg", name: "갤럭시A노랑함마스파이얼", cat: "갤럭시 A타입", finish: "노랑함마", pipe: "스파이얼" },
  { img: "products/p114_갤럭시A동함마스파이얼양옆태엽.jpg", name: "갤럭시A동함마스파이얼양옆태엽", cat: "갤럭시 A타입", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p115_갤럭시A실버함마스파이얼.jpg", name: "갤럭시A실버함마스파이얼", cat: "갤럭시 A타입", finish: "실버함마", pipe: "스파이얼" },
  { img: "products/p116_갤럭시C검정함마스파이얼.jpg", name: "갤럭시C검정함마스파이얼", cat: "갤럭시 C타입", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p117_갤럭시C노랑함마스파이얼.jpg", name: "갤럭시C노랑함마스파이얼", cat: "갤럭시 C타입", finish: "노랑함마", pipe: "스파이얼" },
  { img: "products/p118_갤럭시C동함마스파이얼.jpg", name: "갤럭시C동함마스파이얼", cat: "갤럭시 C타입", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p119_갤럭시C실버함마스파이얼.jpg", name: "갤럭시C실버함마스파이얼", cat: "갤럭시 C타입", finish: "실버함마", pipe: "스파이얼" },
  { img: "products/p120_갤럭시C양옆태엽.jpg", name: "갤럭시C양옆태엽", cat: "갤럭시 C타입", finish: "", pipe: "" },
  { img: "products/p121_갤럭시D검정함마스파이얼.jpg", name: "갤럭시D검정함마스파이얼", cat: "갤럭시 D타입", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p122_갤럭시D노랑함마스파이얼.jpg", name: "갤럭시D노랑함마스파이얼", cat: "갤럭시 D타입", finish: "노랑함마", pipe: "스파이얼" },
  { img: "products/p123_갤럭시D동함마스파이얼.jpg", name: "갤럭시D동함마스파이얼", cat: "갤럭시 D타입", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p124_갤럭시D실버함마스파이얼.jpg", name: "갤럭시D실버함마스파이얼", cat: "갤럭시 D타입", finish: "실버함마", pipe: "스파이얼" },
  { img: "products/p125_사각LED등.jpg", name: "사각LED등", cat: "LED조명", finish: "", pipe: "" },
  { img: "products/p126_스윙태엽_검정함마스파이얼.jpg", name: "스윙태엽 검정함마스파이얼", cat: "파이프", finish: "검정함마", pipe: "스파이얼" },
  { img: "products/p127_스윙태엽_동함마스텐파이프.jpg", name: "스윙태엽 동함마스텐파이프", cat: "파이프", finish: "동함마", pipe: "스텐파이프" },
  { img: "products/p128_스윙태엽_은스텐파이프.jpg", name: "스윙태엽 은스텐파이프", cat: "파이프", finish: "은", pipe: "스텐파이프" },
  { img: "products/p129_양옆태엽_동함마스텐파이프.jpg", name: "양옆태엽 동함마스텐파이프", cat: "양옆태엽[BEST]", finish: "동함마", pipe: "스텐파이프" },
  { img: "products/p130_양옆태엽_동함마스텐파이프210Ø갓_BBQ_Exhaust_Hood_Kore.jpg", name: "양옆태엽 동함마스텐파이프210Ø갓", cat: "양옆태엽[BEST]", finish: "동함마", pipe: "스텐파이프" },
  { img: "products/p131_양옆태엽_스파이얼.jpg", name: "양옆태엽 스파이얼", cat: "양옆태엽[BEST]", finish: "", pipe: "스파이얼" },
  { img: "products/p132_양옆태엽_은스텐파이프.jpg", name: "양옆태엽 은스텐파이프", cat: "양옆태엽[BEST]", finish: "은", pipe: "스텐파이프" },
  { img: "products/p133_양옆태엽_은스텐파이프210Ø갓.jpg", name: "양옆태엽 은스텐파이프210Ø갓", cat: "양옆태엽[BEST]", finish: "은", pipe: "스텐파이프" },
  { img: "products/p134_양옆태엽동함마스텐파이프90-110.jpg", name: "양옆태엽동함마스텐파이프90-110", cat: "양옆태엽[BEST]", finish: "동함마", pipe: "스텐파이프" },
  { img: "products/p135_양옆태엽동함마스파이얼.jpg", name: "양옆태엽동함마스파이얼", cat: "양옆태엽[BEST]", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p136_양옆태엽동함마스파이얼90-110.jpg", name: "양옆태엽동함마스파이얼90-110", cat: "양옆태엽[BEST]", finish: "동함마", pipe: "스파이얼" },
  { img: "products/p137_원형LED등_스텐파이프.jpg", name: "원형LED등,스텐파이프", cat: "LED조명", finish: "", pipe: "스텐파이프" },
  { img: "products/p138_유성에이스_yusungace_양옆태엽_동스텐파이프.jpg", name: "양옆태엽 동스텐파이프", cat: "양옆태엽[BEST]", finish: "동", pipe: "스텐파이프" },
  { img: "products/p139_유성에이스_신형동자바라.jpg", name: "신형동자바라", cat: "후레쉬볼/주름관", finish: "동", pipe: "후레쉬볼" },
  { img: "products/p140_유성에이스_신형신주자바라.jpg", name: "신형신주자바라", cat: "후레쉬볼/주름관", finish: "신주", pipe: "후레쉬볼" },
  { img: "products/p141_유성에이스_신형은자바라.jpg", name: "신형은자바라", cat: "후레쉬볼/주름관", finish: "은", pipe: "후레쉬볼" },
  { img: "products/p142_유성에이스_신형헤어라인자바라.jpg", name: "신형헤어라인자바라", cat: "후레쉬볼/주름관", finish: "헤어라인", pipe: "후레쉬볼" },
  { img: "products/p143_유성에이스_신형흑도금자바라.jpg", name: "신형흑도금자바라", cat: "후레쉬볼/주름관", finish: "흑도금", pipe: "후레쉬볼" },
  { img: "products/p144_유성에이스_은자바라210Ø갓.jpg", name: "은자바라210Ø갓", cat: "후레쉬볼/주름관", finish: "은", pipe: "후레쉬볼" },
  { img: "products/p145_유성에이스_은자바라250Ø갓.jpg", name: "은자바라250Ø갓", cat: "후레쉬볼/주름관", finish: "은", pipe: "후레쉬볼" },
  { img: "products/p146_유성에이스_은자바라320Ø갓.jpg", name: "은자바라320Ø갓", cat: "후레쉬볼/주름관", finish: "은", pipe: "후레쉬볼" },
  { img: "products/p147_유성에이스_은자바라350Ø갓.jpg", name: "은자바라350Ø갓", cat: "후레쉬볼/주름관", finish: "은", pipe: "후레쉬볼" },
  { img: "products/p148_측향동자바라.jpg", name: "측향동자바라", cat: "후레쉬볼/주름관", finish: "동", pipe: "후레쉬볼" },
];

// Total: 148 products
// Total optimized JPEG size: 1.71 MB
// Generated: 2026-05-12
// Sources: retouched (148), shape unique additions (0)

if (typeof module !== "undefined") module.exports = productCatalog;